/*
 * @(#)LocaleElements_it_CH.java	1.6 97/02/24
 *
 * (C) Copyright Taligent, Inc. 1996, 1997 - All Rights Reserved
 * (C) Copyright IBM Corp. 1996, 1997 - All Rights Reserved
 *
 * Portions copyright (c) 1996 Sun Microsystems, Inc. All Rights Reserved.
 *
 *   The original version of this source code and documentation is copyrighted
 * and owned by Taligent, Inc., a wholly-owned subsidiary of IBM. These
 * materials are provided under terms of a License Agreement between Taligent
 * and Sun. This technology is protected by multiple US and International
 * patents. This notice and attribution to Taligent may not be removed.
 *   Taligent is a registered trademark of Taligent, Inc.
 *
 * Permission to use, copy, modify, and distribute this software
 * and its documentation for NON-COMMERCIAL purposes and without
 * fee is hereby granted provided that this copyright notice
 * appears in all copies. Please refer to the file "copyright.html"
 * for further important copyright and licensing information.
 *
 * SUN MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF
 * THE SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
 * TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE, OR NON-INFRINGEMENT. SUN SHALL NOT BE LIABLE FOR
 * ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR
 * DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
 *
 */

/**
 *
 * Table of Java supplied standard locale elements
 *
 * automatically generated by java LocaleTool LocaleElements.java
 *
 * Date Created: Wed Aug 21 15:47:57  1996
 *
 *     Locale Elements and Patterns:  last update 10/23/96
 *
 *
 */

// WARNING : the format of this file will change in the future!

package java.text.resources;

public class LocaleElements_it_CH extends LocaleData {

    public LocaleElements_it_CH() {
        super.init(table);
    }

    static String table []={
        "it_CH", /*locale id based on iso codes*/
        "0810", /*Windows id*/
        "its", /*iso-3 abbrev lang name*/
        "CHE", /*iso-3 abbrev country name*/
        "en_Italian; de_Italienisch; fr_italien; it_italiano", /*language names*/
        "en_Switzerland; de_Schweiz; fr_Suisse; it_Svizzera", /*country names*/
        "gennaio", /*january*/
        "febbraio", /*february*/
        "marzo", /*march*/
        "aprile", /*april*/
        "maggio", /*may*/
        "giugno", /*june*/
        "luglio", /*july*/
        "agosto", /*august*/
        "settembre", /*september*/
        "ottobre", /*october*/
        "novembre", /*november*/
        "dicembre", /*december*/
        "", /*month 13 if applicable*/
        "gen", /*abb january*/
        "feb", /*abb february*/
        "mar", /*abb march*/
        "apr", /*abb april*/
        "mag", /*abb may*/
        "gio", /*abb june*/
        "lug", /*abb july*/
        "ago", /*abb august*/
        "set", /*abb september*/
        "ott", /*abb october*/
        "nov", /*abb november*/
        "dic", /*abb december*/
        "", /*abb month 13 if applicable*/
        "domenica", /*Sunday*/
        "lunedì", /*Monday*/
        "martedì", /*Tuesday*/
        "mercoledì", /*Wednesday*/
        "giovedì", /*Thursday*/
        "venerdì", /*Friday*/
        "sabato", /*Saturday*/
        "dom", /*abb Sunday*/
        "lun", /*abb Monday*/
        "mar", /*abb Tuesday*/
        "mer", /*abb Wednesday*/
        "gio", /*abb Thursday*/
        "ven", /*abb Friday*/
        "sab", /*abb Saturday*/
        "AM", /*am marker*/
        "PM", /*pm marker*/
        "BC;dopo Cristo", /*era strings*/
        "#,##0.###;-#,##0.###", /*decimal pattern*/
        "'Fr. '#,##0.00;'Fr.-'#,##0.00", /*currency pattern*/
        "#,##0%", /*percent pattern*/
        ".", /*decimal separator*/
        "'", /*group (thousands) separator*/
        ";", /*list separator*/
        "%", /*percent sign*/
        "0", /*native 0 digit*/
        "#", /*pattern digit*/
        "-", /*minus sign*/
        "E", /*exponential*/
        "Fr.", /*local currency symbol*/
        "CHF", /*intl currency symbol*/
        ".", /*monetary decimal separator*/
        "H.mm' h' z", /*full time pattern*/
        "HH:mm:ss z", /*long time pattern*/
        "HH:mm:ss", /*medium time pattern*/
        "HH:mm", /*short time pattern*/
        "EEEE, d. MMMM yyyy", /*full date pattern*/
        "d. MMMM yyyy", /*long date pattern*/
        "d-MMM-yy", /*medium date pattern*/
        "dd.MM.yy", /*short date pattern*/
        "{1} {0}", /*date-time pattern*/
        "2", /*first day of week*/
        "4", /*min days in first week*/
        ""
    };
}
