/*
 * @(#)LocaleElements_iw.java	1.3 97/03/03
 *
 * (C) Copyright Taligent, Inc. 1996, 1997 - All Rights Reserved
 * (C) Copyright IBM Corp. 1996, 1997 - All Rights Reserved
 *
 * Portions copyright (c) 1996 Sun Microsystems, Inc. All Rights Reserved.
 *
 *   The original version of this source code and documentation is copyrighted
 * and owned by Taligent, Inc., a wholly-owned subsidiary of IBM. These
 * materials are provided under terms of a License Agreement between Taligent
 * and Sun. This technology is protected by multiple US and International
 * patents. This notice and attribution to Taligent may not be removed.
 *   Taligent is a registered trademark of Taligent, Inc.
 *
 * Permission to use, copy, modify, and distribute this software
 * and its documentation for NON-COMMERCIAL purposes and without
 * fee is hereby granted provided that this copyright notice
 * appears in all copies. Please refer to the file "copyright.html"
 * for further important copyright and licensing information.
 *
 * SUN MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF
 * THE SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
 * TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE, OR NON-INFRINGEMENT. SUN SHALL NOT BE LIABLE FOR
 * ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR
 * DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
 *
 */

/**
 *
 * Table of Java supplied standard locale elements
 *
 * automatically generated by java LocaleTool LocaleElements.java
 *
 * Date Created: Wed Aug 21 15:47:57  1996
 *
 *     Locale Elements and Patterns:  last update 10/23/96
 *
 *
 */

// WARNING : the format of this file will change in the future!

package java.text.resources;

public class LocaleElements_iw extends LocaleData {

    public LocaleElements_iw() {
        super.init(table);
    }

    static String table []={
		/* locale id based on iso codes */        "iw_IL",
		/* Windows id */                          "040d",
		/* iso: 3 character lang name */          "iwb",
		/* iso: 3 character country name */       "ILR",
		/* language names */                      "en_Hebrew; iw_\u05e2\u05d1\u05e8\u05d9\u05ea",
		/* country names */                       "en_Israel; iw_\u05d9\u05e9\u05e8\u05d0\u05dc",
		/* january */                             "\u05E8\u05D0\u05D5\u05E0\u05D9",
		/* february */
		"\u05E8\u05D0\u05D5\u05E8\u05D1\u05E4",
		/* march */                               "\u05E5\u05E8\u05DE",
		/* april */                               "\u05DC\u05D9\u05E8\u05E4\u05D0",
		/* may */                                 "\u05D9\u05D0\u05DE",
		/* june */                                "\u05D9\u05E0\u05D5\u05D9",
		/* july */                                "\u05D9\u05DC\u05D5\u05D9",
		/* august */
		"\u05D8\u05E1\u05D5\u05D2\u05D5\u05D0",
		/* september */
		"\u05E8\u05D1\u05DE\u05D8\u05E4\u05E1",
		/* october */
		"\u05E8\u05D1\u05D5\u05D8\u05E7\u05D5\u05D0",
		/* november */
		"\u05E8\u05D1\u05DE\u05D1\u05D5\u05E0",
		/* december */                            "\u05E8\u05D1\u05DE\u05E6\u05D3",
		/* month 13 if applicable */              "",
		/* abb january */                         "\u05D5\u05E0\u05D9",
		/* abb february */                        "\u05E8\u05D1\u05E4",
		/* abb march */                           "\u05E5\u05E8\u05DE",
		/* abb april */                           "\u05E8\u05E4\u05D0",
		/* abb may */                             "\u05D9\u05D0\u05DE",
		/* abb june */                            "\u05E0\u05D5\u05D9",
		/* abb july */                            "\u05DC\u05D5\u05D9",
		/* abb august */                          "\u05D2\u05D5\u05D0",
		/* abb september */                       "\u05D8\u05E4\u05E1",
		/* abb october */                         "\u05E7\u05D5\u05D0",
		/* abb november */                        "\u05D1\u05D5\u05E0",
		/* abb december */                        "\u05DE\u05E6\u05D3",
		/* abb month 13 if applicable */          "",
		/* sunday */                              "\u05EA\u05D1\u05E9",
		/* monday */                              "\u05DF\u05D5\u05E9\u05D0\u05E8",
		/* tuesday */                             "\u05D9\u05E0\u05E9",
		/* wednesday */                           "\u05D9\u05E9\u05D9\u05DC\u05E9",
		/* thursday */                            "\u05D9\u05E2\u05D9\u05D1\u05E8",
		/* friday */                              "\u05D9\u05E9\u05D9\u05DE\u05D7",
		/* saturday */                            "\u05D9\u05E9\u05E9",
		/* abb sunday */                          "\u0027\u05E9",
		/* abb monday */                          "\u0027\u05D0",
		/* abb tuesday */                         "\u0027\u05D1",
		/* abb wednesday */                       "\u0027\u05D2",
		/* abb thursday */                        "\u0027\u05D3",
		/* abb friday */                          "\u0027\u05D4",
		/* abb saturday */                        "\u0027\u05D5",
		/* am marker; default is AM */            "AM",
		/* pm marker; default is PM */            "PM",
		/* era strings (BC;AD) */                 "\u05dc\u05e1\u05d4\\u0022\u05e0;\u05dc\u05e4\u05e1\u05d4\\u0022\u05e0",
		/* decimal pattern */                     "#,##0.###;-#,##0.###",
		/* currency pattern */
		"\u05D7\u05E9#,##0.##;\u05D7\u05E9-#,##0.##",
		/* percent pattern */                     "#,##0%",
		/* decimal separator */                   ".",
		/* group (thousands) separator */         ",",
		/* list separator  */                     "",
		/* percent sign */                        "%",
		/* native 0 digit */                      "0",
		/* pattern digit */                       "#",
		/* minus sign */                          "-",
		/* exponential */                         "E",
		/* local currency symbol */               "\u05D7\u05E9",
		/* intl currency symbol */                "NIS",
		/* monetary decimal separator */          ",",
		/* Full time pattern */                   "H:mm:ss z",
		/* Long time pattern */                   "H:mm:ss z",
		/* Default time pattern */                "H:mm:ss",
		/* Short time pattern */                  "H:mm",
		/* Full date pattern */                   "EEEE, d MMMM, yyyy",
		/* Long date pattern */                   "d MMMM, yyyy",
		/* Default date pattern */                "dd/MM/yyyy",
		/* Short date pattern */                  "dd/MM/yy",
		/* Date-Time pattern */                   "{0} {1}",
		/* First day of week */                   "1",
		/* Min days in first week*/               "1",
		/* for IW_IL, the following additions are needed: */
		" & Z < \u05D0 " // alef
		+" < \u05D1 " // bet
		+" < \u05D2 " // gimmel
		+" < \u05D3 " // dallet
		+" < \u05D4 " // heh
		+" < \u05D5 " // vav
		+" < \u05D6 " // zain
		+" < \u05D7 " // chet
		+" < \u05D8 " // tet
		+" < \u05D9 " // yod
		+" < \u05DA " // kaf-final
		+" < \u05DB " // kaf
		+" < \u05DC " // lammed
		+" < \u05DD " // mem-final
		+" < \u05DE " // mem
		+" < \u05DF " // nun-final
		+" < \u05E0 " // nun
		+" < \u05E1 " // samech
		+" < \u05E2 " // ain
		+" < \u05E3 " // pe-final
		+" < \u05E4 " // pe
		+" < \u05E5 " // zadi-final
		+" < \u05E6 " // zadi
		+" < \u05E7 " // kof
		+" < \u05E8 " // resh
		+" < \u05E9 " // shin
		+" < \u05EA " // taf
    };
}
