/*
 * @(#)LocaleElements_pl.java	1.6 97/03/03
 *
 * (C) Copyright Taligent, Inc. 1996, 1997 - All Rights Reserved
 * (C) Copyright IBM Corp. 1996, 1997 - All Rights Reserved
 *
 * Portions copyright (c) 1996 Sun Microsystems, Inc. All Rights Reserved.
 *
 *   The original version of this source code and documentation is copyrighted
 * and owned by Taligent, Inc., a wholly-owned subsidiary of IBM. These
 * materials are provided under terms of a License Agreement between Taligent
 * and Sun. This technology is protected by multiple US and International
 * patents. This notice and attribution to Taligent may not be removed.
 *   Taligent is a registered trademark of Taligent, Inc.
 *
 * Permission to use, copy, modify, and distribute this software
 * and its documentation for NON-COMMERCIAL purposes and without
 * fee is hereby granted provided that this copyright notice
 * appears in all copies. Please refer to the file "copyright.html"
 * for further important copyright and licensing information.
 *
 * SUN MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF
 * THE SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
 * TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE, OR NON-INFRINGEMENT. SUN SHALL NOT BE LIABLE FOR
 * ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR
 * DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
 *
 */

/**
 *
 * Table of Java supplied standard locale elements
 *
 * automatically generated by java LocaleTool LocaleElements.java
 *
 * Date Created: Wed Aug 21 15:47:57  1996
 *
 *     Locale Elements and Patterns:  last update 10/23/96
 *
 *
 */

// WARNING : the format of this file will change in the future!

package java.text.resources;

public class LocaleElements_pl extends LocaleData {

    public LocaleElements_pl() {
        super.init(table);
    }

    static String table []={
		/* locale id based on iso codes */        "pl_PL",
		/* Windows id */                          "0415",
		/* iso: 3 character lang name */          "pll",
		/* iso: 3 character country name */       "PLL",
		/* language names */                      "en_Polish; pl_Polski",
		/* country names */                       "en_Poland; pl_Polska",
		/* january */                             "Stycze\u0144",
		/* february */                            "Luty",
		/* march */                               "Marzec",
		/* april */                               "Kwiecie\u0144",
		/* may */                                 "Maj",
		/* june */                                "Czerwiec",
		/* july */                                "Lipiec",
		/* august */                              "Sierpie\u0144",
		/* september */                           "Wrzesie\u0144",
		/* october */                             "Pa\u017adziernik",
		/* november */                            "Listopad",
		/* december */                            "Grudzie\u0144",
		/* month 13 if applicable */              "",
		/* abb january */                         "Styc",
		/* abb february */                        "Luty",
		/* abb march */                           "Marz",
		/* abb april */                           "Kwie",
		/* abb may */                             "Maj",
		/* abb june */                            "Czer",
		/* abb july */                            "Lipi",
		/* abb august */                          "Sier",
		/* abb september */                       "Wrze",
		/* abb october */                         "Pa\u017ad",
		/* abb november */                        "List",
		/* abb december */                        "Grud",
		/* abb month 13 if applicable */          "",
		/* sunday */                              "Niedziela",
		/* monday */                              "Poniedzia\u0142ek",
		/* tuesday */                             "Wtorek",
		/* wednesday */                           "\u015aroda",
		/* thursday */                            "Czwartek",
		/* friday */                              "Pi\u0105tek",
		/* saturday */                            "Sobota",
		/* abb sunday */                          "Ni",
		/* abb monday */                          "Pn",
		/* abb tuesday */                         "Wt",
		/* abb wednesday */                       "\u015ar",
		/* abb thursday */                        "Cz",
		/* abb friday */                          "Pt",
		/* abb saturday */                        "So",
		/* am marker; default is AM */            "AM",
		/* pm marker; default is PM */            "PM",
		/* era strings */                         "p.n.e.;n.e.",
		/* decimal pattern */                     "#,##0.###;-#,##0.###",
		/* currency pattern */                    "Z\u0142#,##0.##;-Z\u0142#,##0.##",
		/* percent pattern */                     "#,##0%",
		/* decimal separator */                   ",",
		/* group (thousands) separator */         ".",
		/* list separator  */                     "",
		/* percent sign */                        "%",
		/* native 0 digit */                      "0",
		/* pattern digit */                       "#",
		/* minus sign */                          "-",
		/* exponential */                         "E",
		/* local currency symbol */               "Z\u0142",
		/* intl currency symbol */                "PLZ ",
		/* monetary decimal separator */          ",",
		/* Full time pattern */                   "H:mm:ss z",
		/* Long time pattern */                   "H:mm:ss z",
		/* Default time pattern */                "H:mm:ss",
		/* Short time pattern */                  "H:mm",
		/* Full date pattern */                   "EEEE, yyyy, MMMM d",
		/* Long date pattern */                   "yyyy, MMMM d",
		/* Default date pattern */                "yyyy-M-d",
		/* Short date pattern */                  "yy-M-d",
		/* Date-Time pattern */                   "{1} {0}",
		/* First day of week */                   "1",
		/* Min days in first week*/               "1",
		/* for pl_PL, default sorting except for the following: */
		/* add d<stroke> between d and e. */
		/* add l<stroke> between l and m. */
		/* add z<abovedot> after z.       */
		"& D < \u0111, \u0110"                       /* d<stroke> */
		+"& L < \u0142, \u0141"                       /* l<stroke> */
		+"& Z < \u017c, \u017b"                            /* z<abovedot> */
    };
}
