/*
 * @(#)LocaleElements_uk.java	1.6 97/03/03
 *
 * (C) Copyright Taligent, Inc. 1996, 1997 - All Rights Reserved
 * (C) Copyright IBM Corp. 1996, 1997 - All Rights Reserved
 *
 * Portions copyright (c) 1996 Sun Microsystems, Inc. All Rights Reserved.
 *
 *   The original version of this source code and documentation is copyrighted
 * and owned by Taligent, Inc., a wholly-owned subsidiary of IBM. These
 * materials are provided under terms of a License Agreement between Taligent
 * and Sun. This technology is protected by multiple US and International
 * patents. This notice and attribution to Taligent may not be removed.
 *   Taligent is a registered trademark of Taligent, Inc.
 *
 * Permission to use, copy, modify, and distribute this software
 * and its documentation for NON-COMMERCIAL purposes and without
 * fee is hereby granted provided that this copyright notice
 * appears in all copies. Please refer to the file "copyright.html"
 * for further important copyright and licensing information.
 *
 * SUN MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF
 * THE SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
 * TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE, OR NON-INFRINGEMENT. SUN SHALL NOT BE LIABLE FOR
 * ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR
 * DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
 *
 */

/**
 *
 * Table of Java supplied standard locale elements
 *
 * automatically generated by java LocaleTool LocaleElements.java
 *
 * Date Created: Wed Aug 21 15:47:57  1996
 *
 *     Locale Elements and Patterns:  last update 10/23/96
 *
 *
 */

// WARNING : the format of this file will change in the future!

package java.text.resources;

public class LocaleElements_uk extends LocaleData {

    public LocaleElements_uk() {
        super.init(table);
    }

    static String table []={
		/* locale id based on iso codes */     "uk_UA",
		/* Windows id */                       "0422",
		/* iso-3 abbrev lang name */           "ukr",
		/* iso-3 abbrev country name */        "UKR",
		/* language names */                   "en_Ukrainian; uk_\u0443\u043A\u0440\u0430\u0457\u043D\u0441\u044C\u043A\u0430",
		/* country names */                    "en_Ukraine; uk_\u0423\u043A\u0440\u0430\u0457\u043D\u0430",
		/* january */                          "\u0441\u0456\u0447\u043D\u044F",
		/* february */                         "\u043B\u044E\u0442\u043E\u0433\u043E",
		/* march */
		"\u0431\u0435\u0440\u0435\u0436\u043D\u044F",
		/* april */                            "\u043A\u0432\u0456\u0442\u043D\u044F",
		/* may */                              "\u0442\u0440\u0430\u0432\u043D\u044F",
		/* june */                             "\u0447\u0435\u0440\u0432\u043D\u044F",
		/* july */                             "\u043B\u0438\u043F\u043D\u044F",
		/* august */                           "\u0441\u0435\u0440\u043F\u043D\u044F",
		/* september */
		"\u0432\u0435\u0440\u0435\u0441\u043D\u044F",
		/* october */                          "\u0416\u043E\u0432\u0442\u043D\u044F",
		/* november */
		"\u043B\u0438\u0441\u0442\u043E\u043F\u0430\u0434\u0430",
		/* december */                         "\u0433\u0440\u0443\u0434\u043D\u044F",
		/* month 13 if applicable */           "",
		/* abb january */                      "\u0441\u0456\u0447",
		/* abb february */                     "\u043B\u044E\u0442",
		/* abb march */                        "\u0431\u0435\u0440",
		/* abb april */                        "\u043A\u0432\u0456\u0442",
		/* abb may */                          "\u0442\u0440\u0430\u0432",
		/* abb june */                         "\u0447\u0435\u0440\u0432",
		/* abb july */                         "\u043B\u0438\u043F",
		/* abb august */                       "\u0441\u0435\u0440\u043F",
		/* abb september */                    "\u0432\u0435\u0440",
		/* abb october */                      "\u0416\u043E\u0432\u0442",
		/* abb november */                     "\u043B\u0438\u0441\u0442",
		/* abb december */                     "\u0433\u0440\u0443\u0434",
		/* abb month 13 if applicable */       "",
		/* sunday */                           "\u043D\u0435\u0434\u0456\u043B\u044F",
		/* monday */
		"\u043F\u043E\u043D\u0435\u0434\u0456\u043B\u043E\u043A",
		/* tuesday */
		"\u0432\u0456\u0432\u0442\u043E\u0440\u043E\u043A",
		/* wednesday */                        "\u0441\u0435\u0440\u0435\u0434\u0430",
		/* thursday */                         "\u0447\u0435\u0442\u0432\u0435\u0440",
		/* friday */
		"\u043F\u0027\u044F\u0442\u043D\u0438\u0446\u044F",
		/* saturday */                         "\u0441\u0443\u0431\u043E\u0442\u0430",
		/* abb sunday */                       "\u043D\u0434",
		/* abb monday */                       "\u043F\u043D",
		/* abb tuesday */                      "\u0432\u0442",
		/* abb wednesday */                    "\u0441\u0440",
		/* abb thursday */                     "\u0447\u0442",
		/* abb friday */                       "\u043F\u0442",
		/* abb saturday */                     "\u0441\u0431",
		/* am marker; default is AM */         "AM",
		/* pm marker; default is PM */         "PM",
		/* era strings */                      "\u0434\u043E \u043D.\u0435.;\u043F\u0456\u0441\u043B\u044F \u043D.\u0435.",
		/* decimal pattern */                  "#,##0.###;-#,##0.###",
		/* currency pattern */
		"#,##0.## \u0433\u0440\u043D;-#,##0.##\u0433\u0440\u043D",
		/* percent pattern */                  "#,##0%",
		/* decimal separator */                ",",
		/* group (thousands) separator */      ".",
		/* list separator */                   "",
		/* percent sign */                     "%",
		/* native 0 digit */                   "0",
		/* pattern digit */                    "#",
		/* minus sign */                       "-",
		/* exponential */                      "E",
		/* local currency symbol */            "\u0433\u0440\u043D",
		/* intl currency symbol */             "UAH",
		/* monetary decimal separator */       ",",
		/* Full time pattern */                "H:mm:ss z",
		/* Long time pattern */                "H:mm:ss z",
		/* Default time pattern */             "H:mm:ss",
		/* Short time pattern */               "H:mm",
		/* Full date pattern */                "EEEE, d, MMMM yyyy",
		/* Long date pattern */                "d, MMMM yyyy",
		/* Default date pattern */             "d/M/yyyy",
		/* Short date pattern */               "d/M/yy",
		/* Date-Time pattern*/                 "{1} {0}",
		/* first day of week */                "1",
		/* min days in first week */           "1",
		/* for uk_UA, default plus the following */
		"& Z < \u0430 , \u0410"  // CYRILLIC A  (small letter, capital letter)
		+ "< \u0431 , \u0411"  // CYRILLIC BE
		+ "< \u0432 , \u0412"  // CYRILLIC VE
		+ "< \u0433 , \u0413"  // CYRILLIC GHE
		+ "< \u0434 , \u0414"  // CYRILLIC DE
		+ "< \u0453 , \u0403"  // macedonian gje
		+ "< \u0452 , \u0402"  // serbian dje
		+ "< \u0435 , \u0415"  // CYRILLIC IE
		+ "< \u0454 , \u0404"  // CYRILLIC UKRAINIAN IE
		+ "< \u0451 , \u0401"  // cyrillic io
		+ "< \u0436 , \u0416"  // CYRILLIC ZHE
		+ "< \u0437 , \u0417"  // CYRILLIC ZE
		+ "< \u0455 , \u0405"  // macedonian dze
		+ "< \u0438 , \u0418"  // CYRILLIC I
		+ "< \u0456 , \u0406"  // CYRILLIC BYELORUSSIAN-UKRAINIAN I
		+ "< \u0457 , \u0407"  // ukrainian yi
		+ "< \u0439 , \u0419"  // cyrillic short i
		+ "< \u0458 , \u0408"  // CYRILLIC JE
		+ "< \u043A , \u041A"  // CYRILLIC KA
		+ "< \u043B , \u041B"  // CYRILLIC EL
		+ "< \u0459 , \u0409"  // CYRILLIC LJE
		+ "< \u043C , \u041C"  // CYRILLIC EM
		+ "< \u043D , \u041D"  // CYRILLIC EN
		+ "< \u045A , \u040A"  // CYRILLIC NJE
		+ "< \u043E , \u041E"  // CYRILLIC O
		+ "< \u043F , \u041F"  // CYRILLIC PE
		+ "< \u0440 , \u0420"  // CYRILLIC ER
		+ "< \u0441 , \u0421"  // CYRILLIC ES
		+ "< \u0442 , \u0422"  // CYRILLIC TE
		+ "< \u045C , \u040C"  // macedonian kje
		+ "< \u045B , \u040B"  // CYRILLIC TSHE
		+ "< \u0443 , \u0423"  // CYRILLIC U
		+ "< \u045E , \u040E"  // byelorussian short u
		+ "< \u0444 , \u0424"  // CYRILLIC EF
		+ "< \u0445 , \u0425"  // CYRILLIC HA
		+ "< \u0446 , \u0426"  // CYRILLIC TSE
		+ "< \u0447 , \u0427"  // CYRILLIC CHE
		+ "< \u045F , \u040F"  // CYRILLIC DZHE
		+ "< \u0448 , \u0428"  // CYRILLIC SHA
		+ "< \u0449 , \u0429"  // CYRILLIC SHCHA
		+ "< \u044A , \u042A"  // CYRILLIC HARD SIGN
		+ "< \u044B , \u042B"  // CYRILLIC YERU
		+ "< \u044C , \u042C"  // CYRILLIC SOFT SIGN
		+ "< \u044D , \u042D"  // CYRILLIC E
		+ "< \u044E , \u042E"  // CYRILLIC YU
		+ "< \u044F , \u042F"  // CYRILLIC YA
		
		/* others, in order, as per unicode.....*/
		
		+ " < \u0461 , \u0460"  // CYRILLIC OMEGA
		+ " < \u0463 , \u0462"  // CYRILLIC YAT
		+ " < \u0465 , \u0464"  // CYRILLIC IOTIFIED E
		+ " < \u0467 , \u0466"  // CYRILLIC LITTLE YUS
		+ " < \u0469 , \u0468"  // CYRILLIC IOTIFIED LITTLE YUS
		+ " < \u046B , \u046A"  // CYRILLIC BIG YUS
		+ " < \u046D , \u046C"  // CYRILLIC IOTIFIED BIG YUS
		+ " < \u046F , \u046E"  // CYRILLIC KSI
		+ " < \u0471 , \u0470"  // CYRILLIC PSI
		+ " < \u0473 , \u0472"  // CYRILLIC FITA
		+ " < \u0475 , \u0474"  // CYRILLIC IZHITSA
		+ " < \u0479 , \u0478"  // CYRILLIC UK
		+ " < \u047B , \u047A"  // CYRILLIC ROUND OMEGA
		+ " < \u047D , \u047C"  // CYRILLIC OMEGA WITH TITLO
		+ " < \u047F , \u047E"  // CYRILLIC OT
		+ " < \u0481 , \u0480"  // CYRILLIC KOPPA
		+ " < \u0491 , \u0490"  // CYRILLIC GHE WITH UPTURN
		+ " < \u0493 , \u0492"  // CYRILLIC GHE WITH STROKE
		+ " < \u0495 , \u0494"  // CYRILLIC GHE WITH MIDDLE HOOK
		+ " < \u0497 , \u0496"  // CYRILLIC ZHE WITH DESCENDER
		+ " < \u0499 , \u0498"  // CYRILLIC ZE WITH DESCENDER
		+ " < \u049B , \u049A"  // CYRILLIC KA WITH DESCENDER
		+ " < \u049D , \u049C"  // CYRILLIC KA WITH VERTICAL STROKE
		+ " < \u049F , \u049E"  // CYRILLIC KA WITH STROKE
		+ " < \u04A1 , \u04A0"  // CYRILLIC BASHKIR KA
		+ " < \u04A3 , \u04A2"  // CYRILLIC EN WITH DESCENDER
		+ " < \u04A5 , \u04A4"  // CYRILLIC LIGATURE EN GHE
		+ " < \u04A7 , \u04A6"  // CYRILLIC PE WITH MIDDLE HOOK
		+ " < \u04A9 , \u04A8"  // CYRILLIC ABKHASIAN HA
		+ " < \u04AB , \u04AA"  // CYRILLIC ES WITH DESCENDER
		+ " < \u04AD , \u04AC"  // CYRILLIC TE WITH DESCENDER
		+ " < \u04AF , \u04AE"  // CYRILLIC STRAIGHT U
		+ " < \u04B1 , \u04B0"  // CYRILLIC STRAIGHT U WITH STROKE
		+ " < \u04B3 , \u04B2"  // CYRILLIC HA WITH DESCENDER
		+ " < \u04B5 , \u04B4"  // CYRILLIC LIGATURE TE TSE
		+ " < \u04B7 , \u04B6"  // CYRILLIC CHE WITH DESCENDER
		+ " < \u04B9 , \u04B8"  // CYRILLIC CHE WITH VERTICAL STROKE
		+ " < \u04BB , \u04BA"  // CYRILLIC SHHA
		+ " < \u04BD , \u04BC"  // CYRILLIC ABKHASIAN CHE
		+ " < \u04BF , \u04BE"  // CYRILLIC ABKHASIAN CHE WITH DESCENDER
		+ " < \u04C4 , \u04C3"  // CYRILLIC KA WITH HOOK
		+ " < \u04C8 , \u04C7"  // CYRILLIC EN WITH HOOK
		+ " < \u04CC , \u04CB"  // CYRILLIC KHAKASSIAN CHE
    };
}
