/*
 * @(#)LocaleElements_el.java	1.8 97/03/10
 *
 * (C) Copyright Taligent, Inc. 1996, 1997 - All Rights Reserved
 * (C) Copyright IBM Corp. 1996, 1997 - All Rights Reserved
 *
 * Portions copyright (c) 1996 Sun Microsystems, Inc. All Rights Reserved.
 *
 *   The original version of this source code and documentation is copyrighted
 * and owned by Taligent, Inc., a wholly-owned subsidiary of IBM. These
 * materials are provided under terms of a License Agreement between Taligent
 * and Sun. This technology is protected by multiple US and International
 * patents. This notice and attribution to Taligent may not be removed.
 *   Taligent is a registered trademark of Taligent, Inc.
 *
 * Permission to use, copy, modify, and distribute this software
 * and its documentation for NON-COMMERCIAL purposes and without
 * fee is hereby granted provided that this copyright notice
 * appears in all copies. Please refer to the file "copyright.html"
 * for further important copyright and licensing information.
 *
 * SUN MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF
 * THE SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
 * TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE, OR NON-INFRINGEMENT. SUN SHALL NOT BE LIABLE FOR
 * ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR
 * DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
 *
 */

/**
 *
 * Table of Java supplied standard locale elements
 *
 * automatically generated by java LocaleTool LocaleElements.java
 *
 * Date Created: Wed Aug 21 15:47:57  1996
 *
 *     Locale Elements and Patterns:  last update 10/23/96
 *
 *
 */

// WARNING : the format of this file will change in the future!

package java.text.resources;

public class LocaleElements_el extends LocaleData {

    public LocaleElements_el() {
        super.init(table);
    }

    static String table []={
        "el_GR", /*locale id based on iso codes*/
        "0408", /*Windows id*/
        "ell",  /*iso-3 abbrev lang name*/
        "GRC",  /*iso-3 abbrev country name*/
        "en_Greek; de_Griechisch; fr_grec; el_\u03b5\u03bb\u03bb\u03b7\u03bd\u03b9\u03ba\u03ac", /*language names*/
        "en_Greece; de_Griechenland; fr_Grece; el_\u0395\u03bb\u03bb\u03ac\u03b4\u03b1", /*country names*/
        "\u0399\u03b1\u03bd\u03bf\u03c5\u03ac\u03c1\u03b9\u03bf\u03B6",  /*january*/
        "\u03a6\u03b5\u03b3\u03c1\u03bf\u03c5\u03ac\u03c1\u03b9\u03bf\u03B6", /*february*/
        "\u039c\u03ac\u03c1\u03c4\u03b9\u03bf\u03B6", /*march*/
        "\u0391\u03c0\u03c1\u03af\u03bb\u03b9\u03bf\u03B6", /*april*/
        "\u039c\u03ac\u0390\u03bf\u03B6", /*may*/
        "\u0399\u03bf\u03cd\u03bd\u03b9\u03bf\u03B6",  /*june*/
        "\u0399\u03bf\u03cd\u03bb\u03b9\u03bf\u03B6", /*july*/
        "\u0391\u03cd\u03b3\u03bf\u03c5\u03c3\u03c4\u03bf\u03B6",  /*august*/
        "\u03a3\u03b5\u03c0\u03c4\u03ad\u03bc\u03b2\u03c1\u03b9\u03bf\u03B6", /*september*/
        "\u039f\u03ba\u03c4\u03cc\u03b2\u03c1\u03b9\u03bf\u03B6", /*october*/
        "\u039d\u03bf\u03ad\u03bc\u03b2\u03c1\u03b9\u03bf\u03B6", /*november*/
        "\u0394\u03b5\u03ba\u03ad\u03bc\u03b2\u03c1\u03b9\u03bf\u03B6", /*december*/
        "",/*month 13 if applicable*/
        "\u0399\u03b1\u03bd", /*abb january*/
        "\u03a6\u03b5\u03b2", /*abb february*/
        "\u039c\u03ac\u03c1", /*abb march*/
        "\u0391\u03c0\u03c1", /*abb april*/
        "\u039c\u03af\u0390", /*abb may*/
        "\u0399\u03bf\u03c5\u03bd", /*abb june*/
        "\u0399\u03bf\u03c5\u03bb", /*abb july*/
        "\u0391\u03cd\u03b3", /*abb august*/
        "\u03a3\u03b5\u03c0", /*abb september*/
        "\u039f\u03ba\u03c4", /*abb october*/
        "\u039d\u03bf\u03b5", /*abb november*/
        "\u0394\u03b5\u03ba", /*abb december*/
        "", /*abb month 13 if applicable*/
        "\u039a\u03c5\u03c1\u03b9\u03b1\u03ba\u03ae", /*Sunday*/
        "\u0394\u03b5\u03c5\u03c4\u03ad\u03c1\u03b1", /*Monday*/
        "\u03a4\u03c1\u03af\u03c4\u03b7", /*Tuesday*/
        "\u03a4\u03b5\u03c4\u03ac\u03c1\u03c4\u03b7", /*Wednesday*/
        "\u03a0\u03ad\u03bc\u03c0\u03c4\u03b7", /*Thursday*/
        "\u03a0\u03b1\u03c1\u03b1\u03c3\u03ba\u03b5\u03c5\u03ae", /*Friday*/
        "\u03a3\u03b1\u03b2\u03b2\u03b1\u03c4\u03bf", /*Saturday*/
        "\u039a\u03c5\u03c1", /*abb Sunday*/
        "\u0394\u03b5\u03c5", /*abb Monday*/
        "\u03a4\u03c1\u03b9", /*abb Tuesday*/
        "\u03a4\u03b5\u03c4", /*abb Wednesday*/
        "\u03a0\u03b5\u03bc", /*abb Thursday*/
        "\u03a0\u03b1\u03c1", /*abb Friday*/
        "\u03a3\u03b1\u03b2", /*abb Saturday*/
        "\u03c0\u03bc", /*am marker*/
        "\u03bc\u03bc", /*pm marker*/
        "BC;AD", /*era strings*/
        "#,##0.###;-#,##0.###", /*decimal pattern*/
        "#,##0.00 \u0394\u03c1\u03c7;-#,##0.00 \u0394\u03c1\u03c7", /*currency pattern*/
        "#,##0%", /*percent pattern*/
        ",", /*decimal separator*/
        ".", /*group (thousands) separator*/
        ";", /*list separator*/
        "%", /*percent sign*/
        "0", /*native 0 digit*/
        "#", /*pattern digit*/
        "-", /*minus sign*/
        "E", /*exponential*/
        "\u0394\u03c1\u03c7", /*local currency symbol*/
        "GRD", /*intl currency symbol*/
        ",", /*monetary decimal separator*/
        "h:mm:ss a z", /*full time pattern*/
        "h:mm:ss a z", /*long time pattern*/
        "h:mm:ss a", /*medium time pattern*/
        "h:mm a", /*short time pattern*/
        "EEEE, d MMMM yyyy", /*full date pattern*/
        "d MMMM yyyy", /*long date pattern*/
        "d MMM yyyy", /*medium date pattern*/
        "d/M/yyyy", /*short date pattern*/
        "{1} {0}", /*date-time pattern*/
        "2", /*first day of week*/
        "1", /*min days in first week*/
		// CollationElements is inherited from Default
		"& Z < \u0391, \u03b1" + // ALPHA, alpha,
		"< \u0386, \u03ac"  + // ALPHA-acute, alpha-acute,
		"< \u0392, \u03b2"  + // BETA, beta,
		"< \u0393, \u03b3"  + // GAMMA, gamma,
		"< \u0394, \u03b4"  + // DELTA, delta,
		"< \u0395, \u03b5"  + // EPSILON, epsilon,
		"< \u0388, \u03ad"  + // EPSILON-acute, epsilon-acute,
		"< \u0396, \u03b6"  + // ZETA, zeta,
		"< \u0397, \u03b7"  + // ETA, eta,
		"< \u0389, \u03ae"  + // ETA-acute, eta-acute,
		"< \u0398, \u03b8"  + // THETA, theta,
		"< \u0399, \u03b9"  + // IOTA, iota,
		"< \u038a, \u03af"  + // IOTA-acute, iota-acute,
		"< \u03aa, \u03ca"  + // IOTA-diaeresis, iota-diaeresis,
		"< \u0390"          + // iota-acute+diaeresis,
		"< \u039a, \u03ba"  + // KAPPA, kappa,
		"< \u039b, \u03bb"  + // LAMBDA, lambda,
		"< \u039c, \u03bc"  + // MU, mu,
		"< \u039d, \u03bd"  + // NU, nu,
		"< \u039e, \u03be"  + // XI, xi,
		"< \u039f, \u03bf"  + // OMICRON, omicron,
		"< \u038c, \u03cc"  + // OMICRON-acute, omicron-acute,
		"< \u03a0, \u03c0"  + // PI, pi,
		"< \u03a1, \u03c1"  + // RHO, rho,
		"< \u03a3, \u03c3"  + // SIGMA, sigma,
		"< \u03c2"          + // sigma-final,
		"< \u03a4, \u03c4"  + // TAU, tau,
		"< \u03a5, \u03c5"  + // UPSILON, upsilon,
		"< \u038e, \u03cd"  + // UPSILON-acute, upsilon-acute,
		"< \u03ab, \u03cb"  + // UPSILON-diaeresis, upsilon-diaeresis,
		"< \u03b0"          + // upsilon-acute+diaeresis,
		"< \u03a6, \u03c6"  + // PHI, phi,
		"< \u03a7, \u03c7"  + // CHI, chi,
		"< \u03a8, \u03c8"  + // PSI, psi,
		"< \u03a9, \u03c9"  + // OMEGA, omega,
		"< \u038f, \u03ce"  + // OMEGA-acute, omega-acute.
		"< A, a < B, b < C, c < D, d < E, e < F, f < G, g < H, h < I, i" +
		"< J, j < K, k < M, m < N, n < P, p < Q, q < R, r < S, s < T, t" +
		"< U, u < V, v < W, w < X, x < Y, y < Z, z" 
    };
}
