/*
 * @(#)LocaleElements_et.java	1.5 97/02/28
 *
 * (C) Copyright Taligent, Inc. 1996, 1997 - All Rights Reserved
 * (C) Copyright IBM Corp. 1996, 1997 - All Rights Reserved
 *
 * Portions copyright (c) 1996 Sun Microsystems, Inc. All Rights Reserved.
 *
 *   The original version of this source code and documentation is copyrighted
 * and owned by Taligent, Inc., a wholly-owned subsidiary of IBM. These
 * materials are provided under terms of a License Agreement between Taligent
 * and Sun. This technology is protected by multiple US and International
 * patents. This notice and attribution to Taligent may not be removed.
 *   Taligent is a registered trademark of Taligent, Inc.
 *
 * Permission to use, copy, modify, and distribute this software
 * and its documentation for NON-COMMERCIAL purposes and without
 * fee is hereby granted provided that this copyright notice
 * appears in all copies. Please refer to the file "copyright.html"
 * for further important copyright and licensing information.
 *
 * SUN MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF
 * THE SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
 * TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE, OR NON-INFRINGEMENT. SUN SHALL NOT BE LIABLE FOR
 * ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR
 * DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
 *
 */

/**
 *
 * Table of Java supplied standard locale elements
 *
 * automatically generated by java LocaleTool LocaleElements.java
 *
 * Date Created: Wed Aug 21 15:47:57  1996
 *
 *     Locale Elements and Patterns:  last update 10/23/96
 *
 *
 */

// WARNING : the format of this file will change in the future!

package java.text.resources;

public class LocaleElements_et extends LocaleData {

    public LocaleElements_et() {
        super.init(table);
    }

    static String table []={
		/* locale id based on iso codes */     "et_EE",
		/* Windows id */                       "0425",
		/* iso-3 abbrev lang name */           "est",
		/* iso-3 abbrev country name */        "EST",
		/* language names */                   "en_Estonian; et_Eesti",
		/* country names */                    "en_Estonia; et_Eesti",
		/* january */                          "Jaanuar",
		/* february */                         "Veebruar",
		/* march */                            "M\u00e4rts",
		/* april */                            "Aprill",
		/* may */                              "Mai",
		/* june */                             "Juuni",
		/* july */                             "Juuli",
		/* august */                           "August",
		/* september */                        "September",
		/* october */                          "Oktoober",
		/* november */                         "November",
		/* december */                         "Detsember",
		/* month 13 if applicable */           "",
		/* abb january */                      "Jaan",
		/* abb february */                     "Veebr",
		/* abb march */                        "M\u00e4rts",
		/* abb april */                        "Apr",
		/* abb may */                          "Mai",
		/* abb june */                         "Juuni",
		/* abb july */                         "Juuli",
		/* abb august */                       "Aug",
		/* abb september */                    "Sept",
		/* abb october */                      "Okt",
		/* abb november */                     "Nov",
		/* abb december */                     "Dets",
		/* abb month 13 if applicable */       "",
		/* sunday */                           "P\u00fchap\u00e4ev",
		/* monday */                           "Esmasp\u00e4ev",
		/* tuesday */                          "Teisip\u00e4ev",
		/* wednesday */                        "Kolmap\u00e4ev",
		/* thursday */                         "Neljap\u00e4ev",
		/* friday */                           "Reede",
		/* saturday */                         "Laup\u00e4ev",
		/* abb sunday */                       "P",
		/* abb monday */                       "E",
		/* abb tuesday */                      "T",
		/* abb wednesday */                    "K",
		/* abb thursday */                     "N",
		/* abb friday */                       "R",
		/* abb saturday */                     "L",
		/* am marker; default is AM */         "AM",
		/* pm marker; default is PM */         "PM",
		/* era strings */                      "e.m.a.;m.a.j.",
		/* decimal pattern */                  "#,##0.###;-#,##0.###",
		/* currency pattern */                 "#,##0.### kr;-#,##0.## kr",
		/* percent pattern */                  "#,##0%",
		/* decimal separator */                ",",
		/* group (thousands) separator */      "\u0020",
		/* list separator */                   "",
		/* percent sign */                     "%",
		/* native 0 digit */                   "0",
		/* pattern digit */                    "#",
		/* minus sign */                       "-",
		/* exponential */                      "E",
		/* local currency symbol */            "kr",
		/* intl currency symbol */             "EEK",
		/* monetary decimal separator */       ",",
		/* Full time pattern */                "HH:mm:ss z",
		/* Long time pattern */                "HH:mm:ss z",
		/* Default time pattern */             "HH:mm:ss",
		/* Short time pattern */               "HH:mm",
		/* Full date pattern */                "EEEE, d, MMMM yyyy",
		/* Long date pattern */                "d, MMMM yyyy",
		/* Default date pattern */             "d-M-yyyy",
		/* Short date pattern */               "d-M-yy",
		/* Date-Time pattern*/                 "{1} {0}",
		/* first day of week */                "1",
		/* min days in first week */           "1",
		//********* COLLATION INFORMATION *************************************
		"@"                                  /* sort accents backwards */
    };
}
