/*
 * @(#)LocaleElements_ro.java	1.5 97/03/10
 *
 * (C) Copyright Taligent, Inc. 1996, 1997 - All Rights Reserved
 * (C) Copyright IBM Corp. 1996, 1997 - All Rights Reserved
 *
 * Portions copyright (c) 1996 Sun Microsystems, Inc. All Rights Reserved.
 *
 *   The original version of this source code and documentation is copyrighted
 * and owned by Taligent, Inc., a wholly-owned subsidiary of IBM. These
 * materials are provided under terms of a License Agreement between Taligent
 * and Sun. This technology is protected by multiple US and International
 * patents. This notice and attribution to Taligent may not be removed.
 *   Taligent is a registered trademark of Taligent, Inc.
 *
 * Permission to use, copy, modify, and distribute this software
 * and its documentation for NON-COMMERCIAL purposes and without
 * fee is hereby granted provided that this copyright notice
 * appears in all copies. Please refer to the file "copyright.html"
 * for further important copyright and licensing information.
 *
 * SUN MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF
 * THE SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
 * TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE, OR NON-INFRINGEMENT. SUN SHALL NOT BE LIABLE FOR
 * ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR
 * DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
 *
 */

/**
 *
 * Table of Java supplied standard locale elements
 *
 * automatically generated by java LocaleTool LocaleElements.java
 *
 * Date Created: Wed Aug 21 15:47:57  1996
 *
 *     Locale Elements and Patterns:  last update 10/23/96
 *
 *
 */

// WARNING : the format of this file will change in the future!

package java.text.resources;

public class LocaleElements_ro extends LocaleData {

    public LocaleElements_ro() {
        super.init(table);
    }

    static String table []={
        /* locale id based on iso codes */     "ro_RO",
        /* Windows id */                       "0418",
        /* iso-3 abbrev lang name */           "rom",
        /* iso-3 abbrev country name */        "ROM",
        /* language names */                   "en_Romanian; ro_rom\u00e2n\u0103",
        /* country names */                    "en_Romania; ro_Rom\u00e2nia",
        /* january */                          "Ianuarie",
        /* february */                         "Februarie",
        /* march */                            "Martie",
        /* april */                            "Aprilie",
        /* may */                              "Mai",
        /* june */                             "Iunie",
        /* july */                             "Iulie",
        /* august */                           "August",
        /* september */                        "Septembrie",
        /* october */                          "Octombrie",
        /* november */                         "Noiembrie",
        /* december */                         "Decembrie",
        /* month 13 if applicable */           "",
        /* abb january */                      "Ian",
        /* abb february */                     "Feb",
        /* abb march */                        "Mar",
        /* abb april */                        "Apr",
        /* abb may */                          "Mai",
        /* abb june */                         "Iun",
        /* abb july */                         "Iul",
        /* abb august */                       "Aug",
        /* abb september */                    "Sep",
        /* abb october */                      "Oct",
        /* abb november */                     "Noe",
        /* abb december */                     "Dec",
        /* abb month 13 if applicable */       "",
        /* sunday */                           "Duminic\u0103",
        /* monday */                           "Luni",
        /* tuesday */                          "Mar\u0163i",
        /* wednesday */                        "Miercuri",
        /* thursday */                         "Joi",
        /* friday */                           "Vineri",
        /* saturday */                         "Simb\u00e1t\u00e1",
        /* abb sunday */                       "D",
        /* abb monday */                       "L",
        /* abb tuesday */                      "Ma",
        /* abb wednesday */                    "Mi",
        /* abb thursday */                     "J",
        /* abb friday */                       "V",
        /* abb saturday */                     "S",
        /* am marker; default is AM */         "AM",
        /* pm marker; default is PM */         "PM",
        /* era strings */                      "d.C.;\u00EE.d.C.",
        /* decimal pattern */                  "#,##0.###;-#,##0.###",
        /* currency pattern */                 "#,##0.00 lei;-#,##0.00 lei",
        /* percent pattern */                  "#,##0%",
        /* decimal separator */                ",",
        /* group (thousands) separator */      ".",
        /* list separator */                   "",
        /* percent sign */                     "%",
        /* native 0 digit */                   "0",
        /* pattern digit */                    "#",
        /* minus sign */                       "-",
        /* exponential */                      "E",
        /* local currency symbol */            "lei",
        /* intl currency symbol */             "ROL",
        /* monetary decimal separator */       ",",
        /* Full time pattern */                "H:mm:ss z",
        /* Long time pattern */                "H:mm:ss z",
        /* Default time pattern */             "H:mm:ss",
        /* Short time pattern */               "H:mm",
        /* Full date pattern */                "EEEE, d, MMMM yyyy",
        /* Long date pattern */                "d, MMMM yyyy",
        /* Default date pattern */             "d.M.yyyy",
        /* Short date pattern */               "d.M.yy",
        /* Date-Time pattern*/                 "{1} {0}",
        /* first day of week */                "1",
        /* min days in first week */           "1",
        " & D < \u0111, \u0110" +                    /* d<stroke>   */
        " & L < \u0142, \u0141" +                    /* l<stroke>   */
        " & Z < \u017c, \u017b"                      /* z<abovedot> */
    };
}
