/*
 * @(#)LocaleElements_sk.java	1.4 97/02/24
 *
 * (C) Copyright Taligent, Inc. 1996, 1997 - All Rights Reserved
 * (C) Copyright IBM Corp. 1996, 1997 - All Rights Reserved
 *
 * Portions copyright (c) 1996 Sun Microsystems, Inc. All Rights Reserved.
 *
 *   The original version of this source code and documentation is copyrighted
 * and owned by Taligent, Inc., a wholly-owned subsidiary of IBM. These
 * materials are provided under terms of a License Agreement between Taligent
 * and Sun. This technology is protected by multiple US and International
 * patents. This notice and attribution to Taligent may not be removed.
 *   Taligent is a registered trademark of Taligent, Inc.
 *
 * Permission to use, copy, modify, and distribute this software
 * and its documentation for NON-COMMERCIAL purposes and without
 * fee is hereby granted provided that this copyright notice
 * appears in all copies. Please refer to the file "copyright.html"
 * for further important copyright and licensing information.
 *
 * SUN MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF
 * THE SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
 * TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE, OR NON-INFRINGEMENT. SUN SHALL NOT BE LIABLE FOR
 * ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR
 * DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
 *
 */

/**
 *
 * Table of Java supplied standard locale elements
 *
 * automatically generated by java LocaleTool LocaleElements.java
 *
 * Date Created: Wed Aug 21 15:47:57  1996
 *
 *     Locale Elements and Patterns:  last update 10/23/96
 *
 *
 */

// WARNING : the format of this file will change in the future!

package java.text.resources;

public class LocaleElements_sk extends LocaleData {

    public LocaleElements_sk() {
        super.init(table);
    }

    static String table []={
		/* locale id based on iso codes */     "sk_SK",
		/* Windows id */                       "041b",
		/* iso-3 abbrev lang name */           "sko",
		/* iso-3 abbrev country name */        "SKO",
		/* language names */                   "en_Slovak; sk_Sloven\u010Dina",
		/* country names */                    "en_Slovakia; sk_Slovensko",
		/* january */                          "Janu\u00e1r",
		/* february */                         "Febru\u00e1r",
		/* march */                            "Marec",
		/* april */                            "Apr\u00edl",
		/* may */                              "M\u00e1j",
		/* june */                             "J\u00fan",
		/* july */                             "J\u00fal",
		/* august */                           "August",
		/* september */                        "September",
		/* october */                          "Okt\u00f3ber",
		/* november */                         "November",
		/* december */                         "December",
		/* month 13 if applicable */           "",
		/* abb january */                      "Jan",
		/* abb february */                     "Feb",
		/* abb march */                        "Mar",
		/* abb april */                        "Apr",
		/* abb may */                          "M\u00e1j",
		/* abb june */                         "J\u00fan",
		/* abb july */                         "J\u00fal",
		/* abb august */                       "Aug",
		/* abb september */                    "Sep",
		/* abb october */                      "Okt",
		/* abb november */                     "Nov",
		/* abb december */                     "Dec",
		/* abb month 13 if applicable */       "",
		/* sunday */                           "Nede\u013ee",
		/* monday */                           "Pondelok",
		/* tuesday */                          "Utorok",
		/* wednesday */                        "Streda",
		/* thursday */                         "\u0160tvrtok",
		/* friday */                           "Piatok",
		/* saturday */                         "Sobota",
		/* abb sunday */                       "Ne",
		/* abb monday */                       "Po",
		/* abb tuesday */                      "Ut",
		/* abb wednesday */                    "St",
		/* abb thursday */                     "\u0160t",
		/* abb friday */                       "Pa",
		/* abb saturday */                     "So",
		/* am marker; default is AM */         "AM",
		/* pm marker; default is PM */         "PM",
		/* era strings */                      "pred n.l.;n.l.",
		/* decimal pattern */                  "#,##0.###;-#,##0.###",
		/* currency pattern */                 "K\u010D #,##0.00 ;-#,##0.00 K\u010D",
		/* percent pattern */                  "#,##0%",
		/* decimal separator */                ",",
		/* group (thousands) separator */      " ",
		/* list separator */                   "",
		/* percent sign */                     "%",
		/* native 0 digit */                   "0",
		/* pattern digit */                    "#",
		/* minus sign */                       "-",
		/* exponential */                      "E",
		/* local currency symbol */            "K\u010D",
		/* intl currency symbol */             "CSK",
		/* monetary decimal separator */       ",",
		/* Full time pattern */                "H:mm:ss z",
		/* Long time pattern */                "H:mm:ss z",
		/* Default time pattern */             "H:mm:ss",
		/* Short time pattern */               "H:mm",
		/* Full date pattern */                "EEEE, yyyy, MMMM d",
		/* Long date pattern */                "yyyy, MMMM d",
		/* Default date pattern */             "yyyy-M-d",
		/* Short date pattern */               "yy-M-d",
		/* Date-Time pattern*/                 "{1} {0}",
		/* first day of week */                "1",
		/* min days in first week */           "1",
		/* for sk_SK, default sorting except for the following: */

		/* add d<stroke> between d and e. */
		/* add ch "ligature" between h and i */
		/* add l<stroke> between l and m. */
		/* add z<abovedot> after z.       */
		"& D < \u0111, \u0110"                       /* d<stroke> */
		+"& H < ch, Ch, cH, CH"                      /* ch ligature */
		+"& L < \u0142, \u0141"                      /* l<stroke> */
		+"& Z < \u017c, \u017b"                      /* z<abovedot> */
    };
}
