/*
 * @(#)LocaleElements_de_CH.java	1.7 97/02/24
 *
 * (C) Copyright Taligent, Inc. 1996, 1997 - All Rights Reserved
 * (C) Copyright IBM Corp. 1996, 1997 - All Rights Reserved
 *
 * Portions copyright (c) 1996 Sun Microsystems, Inc. All Rights Reserved.
 *
 *   The original version of this source code and documentation is copyrighted
 * and owned by Taligent, Inc., a wholly-owned subsidiary of IBM. These
 * materials are provided under terms of a License Agreement between Taligent
 * and Sun. This technology is protected by multiple US and International
 * patents. This notice and attribution to Taligent may not be removed.
 *   Taligent is a registered trademark of Taligent, Inc.
 *
 * Permission to use, copy, modify, and distribute this software
 * and its documentation for NON-COMMERCIAL purposes and without
 * fee is hereby granted provided that this copyright notice
 * appears in all copies. Please refer to the file "copyright.html"
 * for further important copyright and licensing information.
 *
 * SUN MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF
 * THE SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
 * TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE, OR NON-INFRINGEMENT. SUN SHALL NOT BE LIABLE FOR
 * ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR
 * DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
 *
 */

/**
 *
 * Table of Java supplied standard locale elements
 *
 * automatically generated by java LocaleTool LocaleElements.java
 *
 * Date Created: Wed Aug 21 15:47:57  1996
 *
 *     Locale Elements and Patterns:  last update 10/23/96
 *
 *
 */

// WARNING : the format of this file will change in the future!

package java.text.resources;

public class LocaleElements_de_CH extends LocaleData {

    public LocaleElements_de_CH() {
        super.init(table);
    }

    static String table []={
        "de_CH", /*locale id based on iso codes*/
        "0807", /*Windows id*/
        "des", /*iso-3 abbrev lang name*/
        "CHE", /*iso-3 abbrev country name*/
        "en_German; de_Deutsch; fr_allemand", /*language names*/
        "en_Switzerland; de_Schweiz; fr_Suisse; it_Svizzera", /*country names*/
        "Januar", /*january*/
        "Februar", /*february*/
        "März", /*march*/
        "April", /*april*/
        "Mai", /*may*/
        "Juni", /*june*/
        "Juli", /*july*/
        "August", /*august*/
        "September", /*september*/
        "Oktober", /*october*/
        "November", /*november*/
        "Dezember", /*december*/
        "", /*month 13 if applicable*/
        "Jan", /*abb january*/
        "Feb", /*abb february*/
        "Mär", /*abb march*/
        "Apr", /*abb april*/
        "Mai", /*abb may*/
        "Jun", /*abb june*/
        "Jul", /*abb july*/
        "Aug", /*abb august*/
        "Sep", /*abb september*/
        "Okt", /*abb october*/
        "Nov", /*abb november*/
        "Dez", /*abb december*/
        "", /*abb month 13 if applicable*/
        "Sonntag", /*Sunday*/
        "Montag", /*Monday*/
        "Dienstag", /*Tuesday*/
        "Mittwoch", /*Wednesday*/
        "Donnerstag", /*Thursday*/
        "Freitag", /*Friday*/
        "Samstag", /*Saturday*/
        "So", /*abb Sunday*/
        "Mo", /*abb Monday*/
        "Di", /*abb Tuesday*/
        "Mi", /*abb Wednesday*/
        "Do", /*abb Thursday*/
        "Fr", /*abb Friday*/
        "Sa", /*abb Saturday*/
        "AM", /*am marker*/
        "PM", /*pm marker*/
        "v. Chr.;n. Chr.", /*era strings*/
        "#,##0.###;-#,##0.###", /*decimal pattern*/
        "'Fr. '#,##0.00;'Fr.-'#,##0.00", /*currency pattern*/
        "#,##0%", /*percent pattern*/
        ",", /*decimal separator*/
        "'", /*group (thousands) separator*/
        ";", /*list separator*/
        "%", /*percent sign*/
        "0", /*native 0 digit*/
        "#", /*pattern digit*/
        "-", /*minus sign*/
        "E", /*exponential*/
        "Fr.", /*local currency symbol*/
        "CHF", /*intl currency symbol*/
        ".", /*monetary decimal separator*/
        "H.mm' Uhr 'z", /*full time pattern*/
        "HH:mm:ss z", /*long time pattern*/
        "HH:mm:ss", /*medium time pattern*/
        "HH:mm", /*short time pattern*/
        "EEEE, d. MMMM yyyy", /*full date pattern*/
        "d. MMMM yyyy", /*long date pattern*/
        "d.M.yyyy", /*medium date pattern*/
        "d.M.yy", /*short date pattern*/
        "{1} {0}", /*date-time pattern*/
        "2", /*first day of week*/
        "4", /*min days in first week*/
        " & ae , a\u0308" +
        " & AE , A\u0308" +
        " & oe , o\u0308" +
        " & OE , O\u0308" +
        " & ue , u\u0308" +
        " & UE , u\u0308"
    };
}
