/*
 * @(#)LocaleElements_no_NO_NY.java	1.2 97/02/24
 *
 * (C) Copyright Taligent, Inc. 1996, 1997 - All Rights Reserved
 * (C) Copyright IBM Corp. 1996, 1997 - All Rights Reserved
 *
 * Portions copyright (c) 1996 Sun Microsystems, Inc. All Rights Reserved.
 *
 *   The original version of this source code and documentation is copyrighted
 * and owned by Taligent, Inc., a wholly-owned subsidiary of IBM. These
 * materials are provided under terms of a License Agreement between Taligent
 * and Sun. This technology is protected by multiple US and International
 * patents. This notice and attribution to Taligent may not be removed.
 *   Taligent is a registered trademark of Taligent, Inc.
 *
 * Permission to use, copy, modify, and distribute this software
 * and its documentation for NON-COMMERCIAL purposes and without
 * fee is hereby granted provided that this copyright notice
 * appears in all copies. Please refer to the file "copyright.html"
 * for further important copyright and licensing information.
 *
 * SUN MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF
 * THE SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
 * TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE, OR NON-INFRINGEMENT. SUN SHALL NOT BE LIABLE FOR
 * ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR
 * DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
 *
 */

/**
 *
 * Table of Java supplied standard locale elements
 *
 * automatically generated by java LocaleTool LocaleElements.java
 *
 * Date Created: Wed Aug 21 15:47:57  1996
 *
 *     Locale Elements and Patterns:  last update 10/23/96
 *
 *
 */

// WARNING : the format of this file will change in the future!

package java.text.resources;

public class LocaleElements_no_NO_NY extends LocaleData {

    public LocaleElements_no_NO_NY() {
        super.init(table);
    }

    static String table []={
        "no_NO_NY", /*locale id based on iso codes*/
        "0814", /*Windows id*/
        "non", /*iso-3 abbrev lang name*/
        "NOR", /*iso-3 abbrev country name*/
        "en_Norwegian (Nynorsk); de_Norwegisch; fr_norvégien; no_norsk (nynorsk)", /*language names*/
        "en_Norway; de_Norwegen; fr_Norvège; no_Noreg", /*country names*/
        "januar", /*january*/
        "februar", /*february*/
        "mars", /*march*/
        "april", /*april*/
        "mai", /*may*/
        "juni", /*june*/
        "juli", /*july*/
        "august", /*august*/
        "september", /*september*/
        "oktober", /*october*/
        "november", /*november*/
        "desember", /*december*/
        "", /*month 13 if applicable*/
        "jan", /*abb january*/
        "feb", /*abb february*/
        "mar", /*abb march*/
        "apr", /*abb april*/
        "mai", /*abb may*/
        "jun", /*abb june*/
        "jul", /*abb july*/
        "aug", /*abb august*/
        "sep", /*abb september*/
        "okt", /*abb october*/
        "nov", /*abb november*/
        "des", /*abb december*/
        "", /*abb month 13 if applicable*/
        "sundag", /*Sunday*/
        "måndag", /*Monday*/
        "tysdag", /*Tuesday*/
        "onsdag", /*Wednesday*/
        "torsdag", /*Thursday*/
        "fredag", /*Friday*/
        "laurdag", /*Saturday*/
        "su", /*abb Sunday*/
        "må", /*abb Monday*/
        "ty", /*abb Tuesday*/
        "on", /*abb Wednesday*/
        "to", /*abb Thursday*/
        "fr", /*abb Friday*/
        "lau", /*abb Saturday*/
        "AM", /*am marker*/
        "PM", /*pm marker*/
        "BC;AD", /*era strings*/
        "#,##0.###;-#,##0.###", /*decimal pattern*/
        "kr #,##0.00;kr#,##0.00-", /*currency pattern*/
        "#,##0%", /*percent pattern*/
        ",", /*decimal separator*/
        " ", /*group (thousands) separator*/
        ";", /*list separator*/
        "%", /*percent sign*/
        "0", /*native 0 digit*/
        "#", /*pattern digit*/
        "-", /*minus sign*/
        "E", /*exponential*/
        "kr", /*local currency symbol*/
        "NOK", /*intl currency symbol*/
        ",", /*monetary decimal separator*/
        "'kl 'HH.mm z", /*full time pattern*/
        "HH:mm:ss z", /*long time pattern*/
        "HH:mm:ss", /*medium time pattern*/
        "HH:mm", /*short time pattern*/
        "d. MMMM yyyy", /*full date pattern*/
        "d. MMMM yyyy", /*long date pattern*/
        "dd.MMM.yy", /*medium date pattern*/
        "dd.MM.yy", /*short date pattern*/
        "{1} {0}", /*date-time pattern*/
        "2", /*first day of week*/
        "4", /*min days in first week*/
        // Based on "Nordic Cultural Requirements on Information Technology"
        // STRI TS3, 1st Edition.
        " & Z < \u00e6, a\u0308 ,  \u00C6, A\u0308" +
        " < \u00F8, o\u0308, \u00D8, O\u0308" +
		" < a\u030A , A\u030A, aa , aA, Aa , AA" +
        " & y, u\u0308 , Y , U\u0308" +
        " & v, w, V, W "
    };
}
