/*
 * @(#)LocaleElements_is.java	1.6 97/03/03
 *
 * (C) Copyright Taligent, Inc. 1996, 1997 - All Rights Reserved
 * (C) Copyright IBM Corp. 1996, 1997 - All Rights Reserved
 *
 * Portions copyright (c) 1996 Sun Microsystems, Inc. All Rights Reserved.
 *
 *   The original version of this source code and documentation is copyrighted
 * and owned by Taligent, Inc., a wholly-owned subsidiary of IBM. These
 * materials are provided under terms of a License Agreement between Taligent
 * and Sun. This technology is protected by multiple US and International
 * patents. This notice and attribution to Taligent may not be removed.
 *   Taligent is a registered trademark of Taligent, Inc.
 *
 * Permission to use, copy, modify, and distribute this software
 * and its documentation for NON-COMMERCIAL purposes and without
 * fee is hereby granted provided that this copyright notice
 * appears in all copies. Please refer to the file "copyright.html"
 * for further important copyright and licensing information.
 *
 * SUN MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF
 * THE SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
 * TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE, OR NON-INFRINGEMENT. SUN SHALL NOT BE LIABLE FOR
 * ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR
 * DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
 *
 */

/**
 *
 * Table of Java supplied standard locale elements
 *
 * automatically generated by java LocaleTool LocaleElements.java
 *
 * Date Created: Wed Aug 21 15:47:57  1996
 *
 *     Locale Elements and Patterns:  last update 10/23/96
 *
 *
 */

// WARNING : the format of this file will change in the future!

package java.text.resources;

public class LocaleElements_is extends LocaleData {

    public LocaleElements_is() {
        super.init(table);
    }

    static String table []={
		/* locale id based on iso codes */        "is_is",
		/* Windows id */                          "040f",
		/* iso: 3 character lang name */          "ise",
		/* iso: 3 character country name */       "ISE",
		/* language names */                      "en_Icelandic",
		/* country names */                       "en_Iceland",
		/* january */                             "Jan\u00faar",
		/* february */                            "Febr\u00faar",
		/* march */                               "Mars",
		/* april */                               "Apr\u00edl",
		/* may */                                 "Ma\u00ed",
		/* june */                                "J\u00fan\u00ed",
		/* july */                                "J\u00fal\u00ed",
		/* august */                              "\u00c1g\u00fast",
		/* september */                           "September",
		/* october */                             "Okt\u00f3ber",
		/* november */                            "N\u00f3vember",
		/* december */                            "Desember",
		/* month 13 if applicable */              "",
		/* abb january */                         "Jan",
		/* abb february */                        "Feb",
		/* abb march */                           "Mar",
		/* abb april */                           "Apr",
		/* abb may */                             "Ma\u00ed",
		/* abb june */                            "J\u00fan",
		/* abb july */                            "J\u00fal",
		/* abb august */                          "\u00c1g",
		/* abb september */                       "Sep",
		/* abb october */                         "Okt",
		/* abb november */                        "N\u00f3v",
		/* abb december */                        "Des",
		/* abb month 13 if applicable */          "",
		/* sunday */                              "Sunnudagur",
		/* monday */                              "M\u00e1nudagur",
		/* tuesday */                             "\u00FEri\u00F0jundagur",
		/* wednesday */                           "Mi\u00F0vikudagur",
		/* thursday */                            "Fimmtudagur",
		/* friday */                              "F\u00f6studagur",
		/* saturday */                            "Laugardagur",
		/* abb sunday */                          "Sun",
		/* abb monday */                          "M\u00e1n",
		/* abb tuesday */                         "\u00FEri",
		/* abb wednesday */                       "Mi\u00F0",
		/* abb thursday */                        "Fim",
		/* abb friday */                          "F\u00f6s",
		/* abb saturday */                        "Lau",
		/* am marker; default is AM */            "AM",
		/* pm marker; default is PM */            "PM",
		/* era strings */                         "BC;AD",
		/* decimal pattern */                     "#,##0.###;-#,##0.###",
		/* currency pattern */                    "#,##0.## kr;-#,##0.## kr",
		/* percent pattern */                     "#,##0%",
		/* decimal separator */                   ",",
		/* group (thousands) separator */         ".",
		/* list separator  */                     "",
		/* percent sign */                        "%",
		/* native 0 digit */                      "0",
		/* pattern digit */                       "#",
		/* minus sign */                          "-",
		/* exponential */                         "E",
		/* local currency symbol */               "kr",
		/* intl currency symbol */                "ISK",
		/* monetary decimal separator */          ",",
		/* Full time pattern */                   "H:mm:ss z",
		/* Long time pattern */                   "H:mm:ss z",
		/* Default time pattern */                "H:mm:ss",
		/* Short time pattern */                  "H:mm",
		/* Full date pattern */                   "EEEE, d MMMM, yyyy",
		/* Long date pattern */                   "d MMMM, yyyy",
		/* Default date pattern */                "d.M.yyyy",
		/* Short date pattern */                  "d.M.yy",
		/* Date-Time pattern */                   "{1} {0}",
		/* First day of week */                   "1",
		/* Min days in first week*/               "1",
		/* for IS_IS, accents sorted backwards plus the following: */
		
		"@"                                           /* sort accents bkwd */
		
		/* assuming that in the default collation we add:                   */
		/*  thorn, ae ligature, o-diaeresis, and o-slash                    */
		/*  ....in this order...and ditto for the uppercase of these....    */
		/* to be treated as characters (not accented characters) after z    */
		/* then we don't have to add anything here. I've just added it here */
		/* just in case it gets overlooked.                                 */
		
		+"& Z < \u00fe, \u00de < \u00e6, \u00c6 < \u00f6, \u00d6"                  /*   */
		+"< \u00f8, \u00d8"                                            /*   */
    };
}
