/*
 * @(#)LocaleElements_sq.java	1.4 97/02/24
 *
 * (C) Copyright Taligent, Inc. 1996, 1997 - All Rights Reserved
 * (C) Copyright IBM Corp. 1996, 1997 - All Rights Reserved
 *
 * Portions copyright (c) 1996 Sun Microsystems, Inc. All Rights Reserved.
 *
 *   The original version of this source code and documentation is copyrighted
 * and owned by Taligent, Inc., a wholly-owned subsidiary of IBM. These
 * materials are provided under terms of a License Agreement between Taligent
 * and Sun. This technology is protected by multiple US and International
 * patents. This notice and attribution to Taligent may not be removed.
 *   Taligent is a registered trademark of Taligent, Inc.
 *
 * Permission to use, copy, modify, and distribute this software
 * and its documentation for NON-COMMERCIAL purposes and without
 * fee is hereby granted provided that this copyright notice
 * appears in all copies. Please refer to the file "copyright.html"
 * for further important copyright and licensing information.
 *
 * SUN MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF
 * THE SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
 * TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE, OR NON-INFRINGEMENT. SUN SHALL NOT BE LIABLE FOR
 * ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR
 * DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
 *
 */

/**
 *
 * Table of Java supplied standard locale elements
 *
 * automatically generated by java LocaleTool LocaleElements.java
 *
 * Date Created: Wed Aug 21 15:47:57  1996
 *
 *     Locale Elements and Patterns:  last update 10/23/96
 *
 *
 */

// WARNING : the format of this file will change in the future!

package java.text.resources;

public class LocaleElements_sq extends LocaleData {

    public LocaleElements_sq() {
        super.init(table);
    }

    static String table []={
		/* locale id based on iso codes */     "sq_AL",
		/* Windows id */                       "041c",
		/* iso-3 abbrev lang name */           "sqi",
		/* iso-3 abbrev country name */        "ALB",
		/* language names */                   "en_Albanian; sq_Shqipja",
		/* country names */                    "en_Albania; sq_Shqiperia",
		/* january */                          "Janar",
		/* february */                         "Shkurt",
		/* march */                            "Mars",
		/* april */                            "Prill",
		/* may */                              "Maj",
		/* june */                             "Qershor",
		/* july */                             "Korrik",
		/* august */                           "Gusht",
		/* september */                        "Shtator",
		/* october */                          "Tetor",
		/* november */                         "N\u00ebntor",
		/* december */                         "Dhjetor",
		/* month 13 if applicable */           "",
		/* abb january */                      "Jan",
		/* abb february */                     "Shk",
		/* abb march */                        "Mar",
		/* abb april */                        "Pri",
		/* abb may */                          "Maj",
		/* abb june */                         "Qer",
		/* abb july */                         "Kor",
		/* abb august */                       "Gus",
		/* abb september */                    "Sht",
		/* abb october */                      "Tet",
		/* abb november */                     "N\u00ebn",
		/* abb december */                     "Dhj",
		/* abb month 13 if applicable */       "",
		/* sunday */                           "E\u0020Diel\u00eb",
		/* monday */                           "E\u0020H\u003bn\u00eb",
		/* tuesday */                          "E\u0020Mart\u00eb",
		/* wednesday */                        "E\u0020M\u00ebrkur\u00eb",
		/* thursday */                         "E\u0020Enjte",
		/* friday */                           "E\u0020Premte",
		/* saturday */                         "E\u0020Shtun\u00eb",
		/* abb sunday */                       "Die",
		/* abb monday */                       "H\u00ebn",
		/* abb tuesday */                      "Mar",
		/* abb wednesday */                    "M\u00ebr",
		/* abb thursday */                     "Enj",
		/* abb friday */                       "Pre",
		/* abb saturday */                     "Sht",
		/* am marker; default is AM */         "AM",
		/* pm marker; default is PM */         "PM",
		/* era strings */                      "p.e.r.;n.e.r.",
		/* decimal pattern */                  "#,##0.###;-#,##0.###",
		/* currency pattern */                 "Lek#,##0.###;-Lek#,##0.###",
		/* percent pattern */                  "#,##0%",
		/* decimal separator */                ",",
		/* group (thousands) separator */      ".",
		/* list separator */                   "",
		/* percent sign */                     "%",
		/* native 0 digit */                   "0",
		/* pattern digit */                    "#",
		/* minus sign */                       "-",
		/* exponential */                      "E",
		/* local currency symbol */            "Lek",
		/* intl currency symbol */             "ALL",
		/* monetary decimal separator */       ",",
		/* Full time pattern */                "H.mm.ss z",
		/* Long time pattern */                "H.mm.ss z",
		/* Default time pattern */             "H.mm.ss",
		/* Short time pattern */               "H.mm",
		/* Full date pattern */                "EEEE, yyyy, MMMM d",
		/* Long date pattern */                "yyyy, MMMM d",
		/* Default date pattern */             "yyyy-M-d",
		/* Short date pattern */               "yy-M-d",
		/* Date-Time pattern*/                 "{1} {0}",
		/* first day of week */                "1",
		/* min days in first week */           "1",
		"@"                                  /* sort accents backwards */
    };
}
