/*
 * @(#)LocaleElements_lt.java	1.4 97/02/24
 *
 * (C) Copyright Taligent, Inc. 1996, 1997 - All Rights Reserved
 * (C) Copyright IBM Corp. 1996, 1997 - All Rights Reserved
 *
 * Portions copyright (c) 1996 Sun Microsystems, Inc. All Rights Reserved.
 *
 *   The original version of this source code and documentation is copyrighted
 * and owned by Taligent, Inc., a wholly-owned subsidiary of IBM. These
 * materials are provided under terms of a License Agreement between Taligent
 * and Sun. This technology is protected by multiple US and International
 * patents. This notice and attribution to Taligent may not be removed.
 *   Taligent is a registered trademark of Taligent, Inc.
 *
 * Permission to use, copy, modify, and distribute this software
 * and its documentation for NON-COMMERCIAL purposes and without
 * fee is hereby granted provided that this copyright notice
 * appears in all copies. Please refer to the file "copyright.html"
 * for further important copyright and licensing information.
 *
 * SUN MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF
 * THE SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
 * TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE, OR NON-INFRINGEMENT. SUN SHALL NOT BE LIABLE FOR
 * ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR
 * DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
 *
 */

/**
 *
 * Table of Java supplied standard locale elements
 *
 * automatically generated by java LocaleTool LocaleElements.java
 *
 * Date Created: Wed Aug 21 15:47:57  1996
 *
 *     Locale Elements and Patterns:  last update 10/23/96
 *
 *
 */

// WARNING : the format of this file will change in the future!

package java.text.resources;

public class LocaleElements_lt extends LocaleData {

    public LocaleElements_lt() {
        super.init(table);
    }

    static String table []={
		/* locale id based on iso codes */     "lt_LT",
		/* Windows id */                       "0427",
		/* iso-3 abbrev lang name */           "",
		/* iso-3 abbrev country name */        "LTU",
		/* language names */                   "en_Lithuanian; lt_Lietuvi\u0159",
		/* country names */                    "en_Lituania; lt_Lietuva",
		/* january */                          "Sausio",
		/* february */                         "Vasario",
		/* march */                            "Kovo",
		/* april */                            "Baland\u017eio",
		/* may */                              "Gegu\u017e\u0117s",
		/* june */                             "Bir\u017eelio",
		/* july */                             "Liepos",
		/* august */                           "Rugpj\u016b\u010dio",
		/* september */                        "Rugs\u0117jo",
		/* october */                          "Spalio",
		/* november */                         "Lapkri\u010dio",
		/* december */                         "Gruod\u017eio",
		/* month 13 if applicable */           "",
		/* abb january */                      "Sau",
		/* abb february */                     "Vas",
		/* abb march */                        "Kov",
		/* abb april */                        "Bal",
		/* abb may */                          "Geg",
		/* abb june */                         "Bir",
		/* abb july */                         "Lie",
		/* abb august */                       "Rgp",
		/* abb september */                    "Rgs",
		/* abb october */                      "Spa",
		/* abb november */                     "Lap",
		/* abb december */                     "Grd",
		/* abb month 13 if applicable */       "",
		/* sunday */                           "Sekmadienis",
		/* monday */                           "Pirmadienis",
		/* tuesday */                          "Antradienis",
		/* wednesday */                        "Tre\u010diadienis",
		/* thursday */                         "Ketvirtadienis",
		/* friday */                           "Penktadienis",
		/* saturday */                         "\u0160e\u0161tadienis",
		/* abb sunday */                       "Sk",
		/* abb monday */                       "Pr",
		/* abb tuesday */                      "An",
		/* abb wednesday */                    "Tr",
		/* abb thursday */                     "Kt",
		/* abb friday */                       "Pn",
		/* abb saturday */                     "\u0160t",
		/* am marker; default is AM */         "AM",
		/* pm marker; default is PM */         "PM",
		/* era strings */                      "pr.Kr.;po.Kr.",
		/* decimal pattern */                  "##,##0.00;-##,##0.00",
		/* currency pattern */                 "#,##0.## Lt;-#,##0.## Lt",
		/* percent pattern */                  "#,##%",
		/* decimal separator */                ",",
		/* group (thousands) separator */      ".",
		/* list separator */                   "",
		/* percent sign */                     "%",
		/* native 0 digit */                   "0",
		/* pattern digit */                    "#",
		/* minus sign */                       "-",
		/* exponential */                      "E",
		/* local currency symbol */            "Lt",
		/* intl currency symbol */             "LTL",
		/* monetary decimal separator */       ",",
		/* Full time pattern */                "HH.mm.ss z",
		/* Long time pattern */                "HH.mm.ss z",
		/* Default time pattern */             "HH.mm.ss",
		/* Short time pattern */               "HH.mm",
		/* Full date pattern */                "EEEE, yyyy, MMMM d",
		/* Long date pattern */                "yyyy, MMMM d",
		/* Default date pattern */             "yyyy.M.d",
		/* Short date pattern */               "yy.M.d",
		/* Date-Time pattern*/                 "{1} {0}",
		/* first day of week */                "1",
		/* min days in first week */           "1",
		/* for LT_LT, accents sorted backwards plus the following: */
		"@"                                          /* sort accents bkwd */
		
		/* y is sorted between i and j.                                     */
		
		+"& I < y, Y"                                                 /*   */
    };
}
