/*
 * @(#)LocaleElements_ar.java	1.6 97/03/03
 *
 * (C) Copyright Taligent, Inc. 1996, 1997 - All Rights Reserved
 * (C) Copyright IBM Corp. 1996, 1997 - All Rights Reserved
 *
 * Portions copyright (c) 1996 Sun Microsystems, Inc. All Rights Reserved.
 *
 *   The original version of this source code and documentation is copyrighted
 * and owned by Taligent, Inc., a wholly-owned subsidiary of IBM. These
 * materials are provided under terms of a License Agreement between Taligent
 * and Sun. This technology is protected by multiple US and International
 * patents. This notice and attribution to Taligent may not be removed.
 *   Taligent is a registered trademark of Taligent, Inc.
 *
 * Permission to use, copy, modify, and distribute this software
 * and its documentation for NON-COMMERCIAL purposes and without
 * fee is hereby granted provided that this copyright notice
 * appears in all copies. Please refer to the file "copyright.html"
 * for further important copyright and licensing information.
 *
 * SUN MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF
 * THE SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
 * TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE, OR NON-INFRINGEMENT. SUN SHALL NOT BE LIABLE FOR
 * ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR
 * DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
 *
 */

/**
 *
 * Table of Java supplied standard locale elements
 *
 * automatically generated by java LocaleTool LocaleElements.java
 *
 * Date Created: Wed Aug 21 15:47:57  1996
 *
 *     Locale Elements and Patterns:  last update 10/23/96
 *
 *
 */

// WARNING : the format of this file will change in the future!

package java.text.resources;

public class LocaleElements_ar extends LocaleData {

    public LocaleElements_ar() {
        super.init(table);
    }

    static String table []={
		/* locale id based on iso codes */     "ar_EG",
		/* Windows id */                       "0c01",
		/* iso-3 abbrev lang name */           "ara",
		/* iso-3 abbrev country name */        "EGY",
		/* language names */                   "en_Arabic; ar_\u0639\u0631\u064a",
		/* country names */                    "en_Egypt; ar_\u0645\u0635\u0631",
		/* january */                          "\u064A\u0646\u0627\u064A\u0631",
		/* february */                         "\u0641\u0628\u0631\u0627\u064A\u0631",
		/* march */                            "\u0645\u0627\u0631\u0633",
		/* april */                            "\u0625\u0628\u0631\u064A\u0644",
		/* may */                              "\u0645\u0627\u064A\u0648",
		/* june */                             "\u064A\u0648\u0646\u064A\u0647",
		/* july */                             "\u064A\u0648\u0644\u064A\u0647",
		/* august */                           "\u0623\u063A\u0633\u0637\u0633",
		/* september */                        "\u0633\u0628\u062A\u0645\u0628\u0631",
		/* october */                          "\u0623\u0643\u062A\u0648\u0628\u0631",
		/* november */                         "\u0646\u0648\u0641\u0645\u0628\u0631",
		/* december */                         "\u062F\u064A\u0633\u0645\u0628\u0631",
		/* month 13 if applicable */           "",
		/* abb january */                      "\u064A\u0646\u0627",
		/* abb february */                     "\u0641\u0628\u0631",
		/* abb march */                        "\u0645\u0627\u0631",
		/* abb april */                        "\u0625\u0628\u0631",
		/* abb may */                          "\u0645\u0627\u064A",
		/* abb june */                         "\u064A\u0648\u0646",
		/* abb july */                         "\u064A\u0648\u0644",
		/* abb august */                       "\u0623\u063A\u0633",
		/* abb september */                    "\u0633\u0628\u0645",
		/* abb october */                      "\u0623\u0643\u062A",
		/* abb november */                     "\u0646\u0648\u0641",
		/* abb december */                     "\u062F\u064A\u0633",
		/* abb month 13 if applicable */       "",
		/* sunday */                           "\u0627\u0644\u0623\u062D\u062F",
		/* monday */
		"\u0627\u0644\u0623\u062B\u0646\u064A\u0646",
		/* tuesday */
		"\u0627\u0644\u062B\u0644\u0627\u062B\u0627\u0621",
		/* wednesday */
		"\u0627\u0644\u0623\u0631\u0628\u0639\u0627\u0621",
		/* thursday */                         "\u0627\u0644\u062E\u0645\u064A\u0633",
		/* friday */                           "\u0627\u0644\u062C\u0645\u0639\u0647",
		/* saturday */                         "\u0627\u0644\u0633\u0628\u062A",
		/* abb sunday */                       "\u062D",
		/* abb monday */                       "\u0646",
		/* abb tuesday */                      "\u062B",
		/* abb wednesday */                    "\u0631",
		/* abb thursday */                     "\u062E",
		/* abb friday */                       "\u062C",
		/* abb saturday */                     "\u0633",
		/* am marker; default is AM */         "\u0635",
		/* pm marker; default is PM */         "\u0645",
		/* era strings (BC;AD)*/               "\u0645;\u0642\u002E\u0645",
		/* decimal pattern */
		"#,##0.###;#,##0.###-",
		/* currency pattern */
		"\u062C #,##0.###;\u062C#,##0.###-",
		/* percent pattern */                  "#,##0%",
		/* decimal separator */                "\u066B",
		/* group (thousands) separator */      "\u066C",
		/* list separator  */                  "",
		/* percent sign */                     "\u066A",
		/* native 0 digit */                   "\u0660",
		/* pattern digit */                    "#",
		/* minus sign */                       "-",
		/* exponential */                      "",
		/* local currency symbol */            "\u062C",
		/* intl currency symbol */             "EGP",
		/* monetary decimal separator */       ",",
		/* Full time pattern */                "z a h:mm:ss",
		/* Long time pattern */                "z a h:mm:ss",
		/* Default time pattern */             "a h:mm:ss",
		/* Short time pattern */               "a h:mm",
		/* Full date pattern */                "\u0645 yyyy\u060C MMMM d EEEE",
		/* Long date pattern */                "\u0645 yyyy\u060C MMMM d",
		/* Default date pattern */             "\u0645 yyyy/M/d",
		/* Short date pattern */               "\u0645 yy/M/d",
		/* Date-Time pattern*/                 "",
		/* first day of week */                "6",
		/* min days in first week */           "1",
		// for AR_EG, the following additions are needed:
		"& Z < \u0621 "   //  hamza
		+ "< \u0622 "   //  maddaonalef
		+ "< \u0623 "   //  hamzaonalef
		+ "< \u0624 "   //  hamzaonwaw
		+ "< \u0625 "   //  hamzaunderalef
		+ "< \u0626 "   //  hamzaonyeh
		+ "< \u0627 "   //  arabic-alef
		+ "< \u0628 "   //  beh
		+ "< \u0629 "   //  tehmarbuta
		+ "< \u062A "   //  teh
		+ "< \u062B "   //  theh
		+ "< \u062C "   //  jeem
		+ "< \u062D "   //  hah
		+ "< \u062E "   //  khah
		+ "< \u062F "   //  dal
		+ "< \u0630 "   //  thal
		+ "< \u0631 "   //  reh
		+ "< \u0632 "   //  arabic-zain
		+ "< \u0633 "   //  seen
		+ "< \u0634 "   //  sheen
		+ "< \u0635 "   //  sad
		+ "< \u0636 "   //  dad
		+ "< \u0637 "   //  tah
		+ "< \u0638 "   //  zah
		+ "< \u0639 "   //  arabic-ain
		+ "< \u063A "   //  ghain
		+ "< \u0641 "   //  feh
		+ "< \u0642 "   //  qaf
		+ "< \u0643 "   //  arabic-kaf
		+ "< \u0644 "   //  lam
		+ "< \u0645 "   //  meem
		+ "< \u0646 "   //  noon
		+ "< \u0647 "   //  arabic-heh
		+ "< \u0648 "   //  waw
		+ "< \u0649 "   //  alefmaksura
		+ "< \u064A "   //  yeh

		+ "; \u064B "   //  fathatan
		+ "; \u064C "   //  dammatan
		+ "; \u064D "   //  kasratan
		+ "; \u064E "   //  fatha
		+ "; \u064F "   //  damma
		+ "; \u0650 "   //  kasra
		+ "; \u0652 "   //  sukun
		+ "; \u0651 "   //  shadda
    };
}
