/*
 * @(#)LocaleElements_lv.java	1.4 97/02/24
 *
 * (C) Copyright Taligent, Inc. 1996, 1997 - All Rights Reserved
 * (C) Copyright IBM Corp. 1996, 1997 - All Rights Reserved
 *
 * Portions copyright (c) 1996 Sun Microsystems, Inc. All Rights Reserved.
 *
 *   The original version of this source code and documentation is copyrighted
 * and owned by Taligent, Inc., a wholly-owned subsidiary of IBM. These
 * materials are provided under terms of a License Agreement between Taligent
 * and Sun. This technology is protected by multiple US and International
 * patents. This notice and attribution to Taligent may not be removed.
 *   Taligent is a registered trademark of Taligent, Inc.
 *
 * Permission to use, copy, modify, and distribute this software
 * and its documentation for NON-COMMERCIAL purposes and without
 * fee is hereby granted provided that this copyright notice
 * appears in all copies. Please refer to the file "copyright.html"
 * for further important copyright and licensing information.
 *
 * SUN MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF
 * THE SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
 * TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE, OR NON-INFRINGEMENT. SUN SHALL NOT BE LIABLE FOR
 * ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR
 * DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
 *
 */

/**
 *
 * Table of Java supplied standard locale elements
 *
 * automatically generated by java LocaleTool LocaleElements.java
 *
 * Date Created: Wed Aug 21 15:47:57  1996
 *
 *     Locale Elements and Patterns:  last update 10/23/96
 *
 *
 */

// WARNING : the format of this file will change in the future!

package java.text.resources;

public class LocaleElements_lv extends LocaleData {

    public LocaleElements_lv() {
        super.init(table);
    }

    static String table []={
		/* locale id based on iso codes */     "lv_LV",
		/* Windows id */                       "0426",
		/* iso-3 abbrev lang name */           "",
		/* iso-3 abbrev country name */        "LVA",
		/* language names */                   "en_Latvian; lv_Latvie\u0161u",
		/* country names */                    "en_Latvia; lv_Latvija",
		/* january */                          "Janv\u0101ris",
		/* february */                         "Febru\u0101ris",
		/* march */                            "Marts",
		/* april */                            "Apr\u012blis",
		/* may */                              "Maijs",
		/* june */                             "J\u016bnijs",
		/* july */                             "J\u016blijs",
		/* august */                           "Augusts",
		/* september */                        "Septembris",
		/* october */                          "Oktobris",
		/* november */                         "Novembris",
		/* december */                         "Decembris",
		/* month 13 if applicable */           "",
		/* abb january */                      "Jan",
		/* abb february */                     "Feb",
		/* abb march */                        "Mar",
		/* abb april */                        "Apr",
		/* abb may */                          "Maijs",
		/* abb june */                         "J\u016bn",
		/* abb july */                         "J\u016bl",
		/* abb august */                       "Aug",
		/* abb september */                    "Sep",
		/* abb october */                      "Okt",
		/* abb november */                     "Nov",
		/* abb december */                     "Dec",
		/* abb month 13 if applicable */       "",
		/* sunday */                           "Sv\u0113tdiena",
		/* monday */                           "Pirmdiena",
		/* tuesday */                          "Otrdiena",
		/* wednesday */                        "Tre\u0161diena",
		/* thursday */                         "Ceturdien",
		/* friday */                           "Piektdiena",
		/* saturday */                         "Sestdiena",
		/* abb sunday */                       "Sv",
		/* abb monday */                       "P",
		/* abb tuesday */                      "O",
		/* abb wednesday */                    "T",
		/* abb thursday */                     "C",
		/* abb friday */                       "Pk",
		/* abb saturday */                     "S",
		/* am marker; default is AM */         "AM",
		/* pm marker; default is PM */         "PM",
		/* era strings */                      "pm\u0113;m\u0113",
		/* decimal pattern */                  "#,##0.###;-#,##0.###",
		/* currency pattern */                 "#,##0.## Ls;-#,##0.## Ls",
		/* percent pattern */                  "#,##0%",
		/* decimal separator */                ",",
		/* group (thousands) separator */      "\u0020", // Space.
		/* list separator */                   "",
		/* percent sign */                     "%",
		/* native 0 digit */                   "0",
		/* pattern digit */                    "#",
		/* minus sign */                       "-",
		/* exponential */                      "E",
		/* local currency symbol */            "Ls",
		/* intl currency symbol */             "LVL",
		/* monetary decimal separator */       ",",
		/* Full time pattern */                "HH:mm:ss z",
		/* Long time pattern */                "HH:mm:ss z",
		/* Default time pattern */             "HH:mm:ss",
		/* Short time pattern */               "HH:mm",
		/* Full date pattern */                "EEEE, yyyy, d MMMM",
		/* Long date pattern */                "yyyy, d MMMM",
		/* Default date pattern */             "yyyy.d.M",
		/* Short date pattern */               "yy.d.M",
		/* Date-Time pattern*/                 "{1} {0}",
		/* first day of week */                "1",
		/* min days in first week */           "1",
		/* for LV_LV, accents sorted backwards plus the following: */
		
		"@"                                          /* sort accents bkwd */
		
		/* y is sorted between i and j.                                     */
		
		+"& I < y, Y"                                                 /*   */
    };
}
