/*
 * @(#)LocaleElements_fr_CH.java	1.6 97/02/24
 *
 * (C) Copyright Taligent, Inc. 1996, 1997 - All Rights Reserved
 * (C) Copyright IBM Corp. 1996, 1997 - All Rights Reserved
 *
 * Portions copyright (c) 1996 Sun Microsystems, Inc. All Rights Reserved.
 *
 *   The original version of this source code and documentation is copyrighted
 * and owned by Taligent, Inc., a wholly-owned subsidiary of IBM. These
 * materials are provided under terms of a License Agreement between Taligent
 * and Sun. This technology is protected by multiple US and International
 * patents. This notice and attribution to Taligent may not be removed.
 *   Taligent is a registered trademark of Taligent, Inc.
 *
 * Permission to use, copy, modify, and distribute this software
 * and its documentation for NON-COMMERCIAL purposes and without
 * fee is hereby granted provided that this copyright notice
 * appears in all copies. Please refer to the file "copyright.html"
 * for further important copyright and licensing information.
 *
 * SUN MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF
 * THE SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
 * TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE, OR NON-INFRINGEMENT. SUN SHALL NOT BE LIABLE FOR
 * ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR
 * DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
 *
 */

/**
 *
 * Table of Java supplied standard locale elements
 *
 * automatically generated by java LocaleTool LocaleElements.java
 *
 * Date Created: Wed Aug 21 15:47:57  1996
 *
 *     Locale Elements and Patterns:  last update 10/23/96
 *
 *
 */

// WARNING : the format of this file will change in the future!

package java.text.resources;

public class LocaleElements_fr_CH extends LocaleData {

    public LocaleElements_fr_CH() {
        super.init(table);
    }

    static String table []={
        "fr_CH", /*locale id based on iso codes*/
        "100c", /*Windows id*/
        "frs", /*iso-3 abbrev lang name*/
        "CHE", /*iso-3 abbrev country name*/
        "en_French; de_Französisch; fr_français", /*language names*/
        "en_Switzerland; de_Schweiz; fr_Suisse; it_Svizzera", /*country names*/
        "janvier", /*january*/
        "février", /*february*/
        "mars", /*march*/
        "avril", /*april*/
        "mai", /*may*/
        "juin", /*june*/
        "juillet", /*july*/
        "août", /*august*/
        "septembre", /*september*/
        "octobre", /*october*/
        "novembre", /*november*/
        "décembre", /*december*/
        "", /*month 13 if applicable*/
        "janv.", /*abb january*/
        "févr.", /*abb february*/
        "mar", /*abb march*/
        "avr.", /*abb april*/
        "mai", /*abb may*/
        "jun", /*abb june*/
        "juil.", /*abb july*/
        "août", /*abb august*/
        "sept.", /*abb september*/
        "oct.", /*abb october*/
        "nov.", /*abb november*/
        "déc.", /*abb december*/
        "", /*abb month 13 if applicable*/
        "dimanche", /*Sunday*/
        "lundi", /*Monday*/
        "mardi", /*Tuesday*/
        "mercredi", /*Wednesday*/
        "jeudi", /*Thursday*/
        "vendredi", /*Friday*/
        "samedi", /*Saturday*/
        "di", /*abb Sunday*/
        "lu", /*abb Monday*/
        "ma", /*abb Tuesday*/
        "me", /*abb Wednesday*/
        "je", /*abb Thursday*/
        "ve", /*abb Friday*/
        "sa", /*abb Saturday*/
        "AM", /*am marker*/
        "PM", /*pm marker*/
        "BC;ap. J.-C.", /*era strings*/
        "#,##0.###;-#,##0.###", /*decimal pattern*/
        "'Fr. '#,##0.00;'Fr.-'#,##0.00", /*currency pattern*/
        "#,##0%", /*percent pattern*/
        ".", /*decimal separator*/
        "'", /*group (thousands) separator*/
        ";", /*list separator*/
        "%", /*percent sign*/
        "0", /*native 0 digit*/
        "#", /*pattern digit*/
        "-", /*minus sign*/
        "E", /*exponential*/
        "Fr.", /*local currency symbol*/
        "CHF", /*intl currency symbol*/
        ".", /*monetary decimal separator*/
        "HH.mm.' h' z", /*full time pattern*/
        "HH:mm:ss z", /*long time pattern*/
        "HH:mm:ss", /*medium time pattern*/
        "HH:mm", /*short time pattern*/
        "EEEE, d. MMMM yyyy", /*full date pattern*/
        "d. MMMM yyyy", /*long date pattern*/
        "d MMM yy", /*medium date pattern*/
        "dd.MM.yy", /*short date pattern*/
        "{1} {0}", /*date-time pattern*/
        "2", /*first day of week*/
        "4", /*min days in first week*/
        "@"
    };
}
