/*
 * @(#)LocaleElements_fi.java	1.4 97/02/24
 *
 * (C) Copyright Taligent, Inc. 1996, 1997 - All Rights Reserved
 * (C) Copyright IBM Corp. 1996, 1997 - All Rights Reserved
 *
 * Portions copyright (c) 1996 Sun Microsystems, Inc. All Rights Reserved.
 *
 *   The original version of this source code and documentation is copyrighted
 * and owned by Taligent, Inc., a wholly-owned subsidiary of IBM. These
 * materials are provided under terms of a License Agreement between Taligent
 * and Sun. This technology is protected by multiple US and International
 * patents. This notice and attribution to Taligent may not be removed.
 *   Taligent is a registered trademark of Taligent, Inc.
 *
 * Permission to use, copy, modify, and distribute this software
 * and its documentation for NON-COMMERCIAL purposes and without
 * fee is hereby granted provided that this copyright notice
 * appears in all copies. Please refer to the file "copyright.html"
 * for further important copyright and licensing information.
 *
 * SUN MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF
 * THE SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
 * TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE, OR NON-INFRINGEMENT. SUN SHALL NOT BE LIABLE FOR
 * ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR
 * DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
 *
 */

/**
 *
 * Table of Java supplied standard locale elements
 *
 * automatically generated by java LocaleTool LocaleElements.java
 *
 * Date Created: Wed Aug 21 15:47:57  1996
 *
 *     Locale Elements and Patterns:  last update 10/23/96
 *
 *
 */

// WARNING : the format of this file will change in the future!

package java.text.resources;

public class LocaleElements_fi extends LocaleData {

    public LocaleElements_fi() {
        super.init(table);
    }

    static String table []={
        "fi_FI", /*locale id based on iso codes*/
        "040b", /*Windows id*/
        "fin", /*iso-3 abbrev lang name*/
        "FIN", /*iso-3 abbrev country name*/
        "en_Finnish; de_Finnisch; fr_finnois; fi_suomi", /*language names*/
        "en_Finland; de_Finnland; fr_Finlande; fi_Suomi", /*country names*/
        "tammikuu", /*january*/
        "helmikuu", /*february*/
        "maaliskuu", /*march*/
        "huhtikuu", /*april*/
        "toukokuu", /*may*/
        "kesäkuu", /*june*/
        "heinäkuu", /*july*/
        "elokuu", /*august*/
        "syyskuu", /*september*/
        "lokakuu", /*october*/
        "marraskuu", /*november*/
        "joulukuu", /*december*/
        "", /*month 13 if applicable*/
        "tammi", /*abb january*/
        "helmi", /*abb february*/
        "maalis", /*abb march*/
        "huhti", /*abb april*/
        "touko", /*abb may*/
        "kesä", /*abb june*/
        "heinä", /*abb july*/
        "elo", /*abb august*/
        "syys", /*abb september*/
        "loka", /*abb october*/
        "marras", /*abb november*/
        "joulu", /*abb december*/
        "", /*abb month 13 if applicable*/
        "sunnuntai", /*Sunday*/
        "maanantai", /*Monday*/
        "tiistai", /*Tuesday*/
        "keskiviikko", /*Wednesday*/
        "torstai", /*Thursday*/
        "perjantai", /*Friday*/
        "lauantai", /*Saturday*/
        "su", /*abb Sunday*/
        "ma", /*abb Monday*/
        "ti", /*abb Tuesday*/
        "ke", /*abb Wednesday*/
        "to", /*abb Thursday*/
        "pe", /*abb Friday*/
        "la", /*abb Saturday*/
        "AM", /*am marker*/
        "PM", /*pm marker*/
        "BC;AD", /*era strings*/
        "#,##0.###;-#,##0.###", /*decimal pattern*/
        "#,##0.00 mk;-#,##0.00 mk", /*currency pattern*/
        "#,##0%", /*percent pattern*/
        ",", /*decimal separator*/
        " ", /*group (thousands) separator*/
        ";", /*list separator*/
        "%", /*percent sign*/
        "0", /*native 0 digit*/
        "#", /*pattern digit*/
        "-", /*minus sign*/
        "E", /*exponential*/
        "mk", /*local currency symbol*/
        "FIM", /*intl currency symbol*/
        ",", /*monetary decimal separator*/
        "H:mm:ss z", /*full time pattern*/
        "H:mm:ss z", /*long time pattern*/
        "H:mm:ss", /*medium time pattern*/
        "H:mm", /*short time pattern*/
        "d. MMMM'ta 'yyyy", /*full date pattern*/
        "d. MMMM'ta 'yyyy", /*long date pattern*/
        "dd.MM.yyyy", /*medium date pattern*/
        "dd.MM.yy", /*short date pattern*/
        "{1} {0}", /*date-time pattern*/
        "2", /*first day of week*/
        "4", /*min days in first week*/
        " & Z < a\u030A , A\u030A " +      // a-ring and A-ring
        " < a\u0308 , A\u0308 " +          // a-umlaut and A-umlaut
        " < o\u0308 , O\u0308 " +          // o-umlaut and O-umlaut
        " & U < w , W ; v " +              // optional, insert b4 v
        " & X < u\u0308 , U\u0308 ; y "    // optional, insert b4 y
    };
}
