/*
 * @(#)LocaleElements_bg.java	1.6 97/03/03
 *
 * (C) Copyright Taligent, Inc. 1996, 1997 - All Rights Reserved
 * (C) Copyright IBM Corp. 1996, 1997 - All Rights Reserved
 *
 * Portions copyright (c) 1996 Sun Microsystems, Inc. All Rights Reserved.
 *
 *   The original version of this source code and documentation is copyrighted
 * and owned by Taligent, Inc., a wholly-owned subsidiary of IBM. These
 * materials are provided under terms of a License Agreement between Taligent
 * and Sun. This technology is protected by multiple US and International
 * patents. This notice and attribution to Taligent may not be removed.
 *   Taligent is a registered trademark of Taligent, Inc.
 *
 * Permission to use, copy, modify, and distribute this software
 * and its documentation for NON-COMMERCIAL purposes and without
 * fee is hereby granted provided that this copyright notice
 * appears in all copies. Please refer to the file "copyright.html"
 * for further important copyright and licensing information.
 *
 * SUN MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF
 * THE SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
 * TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE, OR NON-INFRINGEMENT. SUN SHALL NOT BE LIABLE FOR
 * ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR
 * DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
 *
 */

/**
 *
 * Table of Java supplied standard locale elements
 *
 * automatically generated by java LocaleTool LocaleElements.java
 *
 * Date Created: Wed Aug 21 15:47:57  1996
 *
 *     Locale Elements and Patterns:  last update 10/23/96
 *
 *
 */

// WARNING : the format of this file will change in the future!

package java.text.resources;

public class LocaleElements_bg extends LocaleData {

    public LocaleElements_bg() {
        super.init(table);
    }

    static String table []={
		/* locale id based on iso codes */        "bg_BG",
		/* Windows id */                          "0402",
		/* iso: 3 character lang name */          "bgl",
		/* iso: 3 character country name */       "BGL",
		/* language names */                      "en_Bulgarian; bg_\u0431\u044A\u043B\u0433\u0430\u0440\u0441\u043A\u0438",
		/* country names */                       "en_Bulgaria; bg_\u0411\u044A\u043B\u0433\u0430\u0440\u0438\u044F",
		/* january */
		"\u042F\u043D\u0443\u0430\u0440\u0438",
		/* february */
		"\u0424\u0435\u0432\u0440\u0443\u0430\u0440\u0438",
		/* march */                               "\u041C\u0430\u0440\u0442",
		/* april */
		"\u0410\u043F\u0440\u0438\u043B",
		/* may */                                 "\u041C\u0430\u0439",
		/* june */                                "\u042E\u043D\u0438",
		/* july */                                "\u042E\u043B\u0438",
		/* august */
		"\u0410\u0432\u0433\u0443\u0441\u0442",
		/* september */
		"\u0421\u0435\u043F\u0442\u0435\u043C\u0432\u0440\u0438",
		/* october */
		"\u041E\u043A\u0442\u043E\u043C\u0432\u0440\u0438",
		/* november */
		"\u041D\u043E\u0435\u043C\u0432\u0440\u0438",
		/* december */
		"\u0414\u0435\u043A\u0435\u043C\u0432\u0440\u0438",
		/* month 13 if applicable */              "",
		/* abb january */                         "I",
		/* abb february */                        "II",
		/* abb march */                           "III",
		/* abb april */                           "IV",
		/* abb may */                             "V",
		/* abb june */                            "VI",
		/* abb july */                            "VII",
		/* abb august */                          "VIII",
		/* abb september */                       "IX",
		/* abb october */                         "X",
		/* abb november */                        "XI",
		/* abb december */                        "XII",
		/* abb month 13 if applicable */          "",
		/* sunday */
		"\u0421\u044A\u0431\u043E\u0442\u0430",
		/* monday */
		"\u041D\u0435\u0434\u0435\u043B\u044F",
		/* tuesday */
		"\u041F\u043E\u043D\u0435\u0434\u0435\u043B\u043D\u0438\u043A",
		/* wednesday */
		"\u0412\u0442\u043E\u0440\u043D\u0438\u043A",
		/* thursday */
		"\u0421\u0440\u044F\u0434\u0430",
		/* friday */
		"\u0427\u0435\u0442\u0432\u044A\u0440\u0442\u044A\u043A",
		/* saturday */
		"\u041F\u0435\u0442\u044A\u043A",
		/* abb sunday */                          "\u0421\u0431",
		/* abb monday */                          "\u041D\u0434",
		/* abb tuesday */                         "\u041F\u043D",
		/* abb wednesday */                       "\u0412\u0442",
		/* abb thursday */                        "\u0421\u0440",
		/* abb friday */                          "\u0427\u0442",
		/* abb saturday */                        "\u041F\u0442",
		/* am marker; default is AM */            "AM",
		/* pm marker; default is PM */            "PM",
		/* era strings */                         "\u043F\u0440.\u043D.\u0435.;\u043D.\u0435.",
		/* decimal pattern */                     "#,##0.###;-#,##0.###",
		/* currency pattern */                    "Lv#,##0.##;-Lv#,##0.##",
		/* percent pattern */                     "#,##0%",
		/* decimal separator */                   ",",
		/* group (thousands) separator */         ".",
		/* list separator  */                     "",
		/* percent sign */                        "%",
		/* native 0 digit */                      "0",
		/* pattern digit */                       "#",
		/* minus sign */                          "-",
		/* exponential */                         "E",
		/* local currency symbol */               "Lv",
		/* intl currency symbol */                "BGL",
		/* monetary decimal separator */          ",",
		/* Full time pattern */                   "H:mm:ss z",
		/* Long time pattern */                   "H:mm:ss z",
		/* Default time pattern */                "H:mm:ss",
		/* Short time pattern */                  "H:mm",
		/* Full date pattern */                   "EEEE, yyyy, MMMM d",
		/* Long date pattern */                   "yyyy, MMMM d ",
		/* Default date pattern */                "yyyy-M-d",
		/* Short date pattern */                  "yy-M-d",
		/* Date-Time pattern */                   "{1} {0}",
		/* First day of week */                   "1",
		/* Min days in first week*/               "1",
		/* for BG_BG, default plus the following */
		"& Z < \u0430 , \u0410"  // CYRILLIC A  (small letter, capital letter)
		+ "< \u0431 , \u0411"  // CYRILLIC BE
		+ "< \u0432 , \u0412"  // CYRILLIC VE
		+ "< \u0433 , \u0413"  // CYRILLIC GHE
		+ "< \u0434 , \u0414"  // CYRILLIC DE
		+ "< \u0453 , \u0403"  // macedonian gje
		+ "< \u0452 , \u0402"  // serbian dje
		+ "< \u0435 , \u0415"  // CYRILLIC IE
		+ "< \u0454 , \u0404"  // CYRILLIC UKRAINIAN IE
		+ "< \u0451 , \u0401"  // cyrillic io
		+ "< \u0436 , \u0416"  // CYRILLIC ZHE
		+ "< \u0437 , \u0417"  // CYRILLIC ZE
		+ "< \u0455 , \u0405"  // macedonian dze
		+ "< \u0438 , \u0418"  // CYRILLIC I
		+ "< \u0456 , \u0406"  // CYRILLIC BYELORUSSIAN-UKRAINIAN I
		+ "< \u0457 , \u0407"  // ukrainian yi
		+ "< \u0458 , \u0408"  // CYRILLIC JE
		+ "< \u043A , \u041A"  // CYRILLIC KA
		+ "< \u043B , \u041B"  // CYRILLIC EL
		+ "< \u0459 , \u0409"  // CYRILLIC LJE
		+ "< \u043C , \u041C"  // CYRILLIC EM
		+ "< \u043D , \u041D"  // CYRILLIC EN
		+ "< \u045A , \u040A"  // CYRILLIC NJE
		+ "< \u043E , \u041E"  // CYRILLIC O
		+ "< \u043F , \u041F"  // CYRILLIC PE
		+ "< \u0440 , \u0420"  // CYRILLIC ER
		+ "< \u0441 , \u0421"  // CYRILLIC ES
		+ "< \u0442 , \u0422"  // CYRILLIC TE
		+ "< \u045C , \u040C"  // macedonian kje
		+ "< \u045B , \u040B"  // CYRILLIC TSHE
		+ "< \u0443 , \u0423"  // CYRILLIC U
		+ "< \u045E , \u040E"  // byelorussian short u
		+ "< \u0444 , \u0424"  // CYRILLIC EF
		+ "< \u0445 , \u0425"  // CYRILLIC HA
		+ "< \u0446 , \u0426"  // CYRILLIC TSE
		+ "< \u0447 , \u0427"  // CYRILLIC CHE
		+ "< \u045F , \u040F"  // CYRILLIC DZHE
		+ "< \u0448 , \u0428"  // CYRILLIC SHA
		+ "< \u0449 , \u0429"  // CYRILLIC SHCHA
		+ "< \u044A , \u042A"  // CYRILLIC HARD SIGN
		+ "< \u044B , \u042B"  // CYRILLIC YERU
		+ "< \u044C , \u042C"  // CYRILLIC SOFT SIGN
		+ "< \u044D , \u042D"  // CYRILLIC E
		+ "< \u044E , \u042E"  // CYRILLIC YU
		+ "< \u044F , \u042F"  // CYRILLIC YA

		/* others, in order, as per unicode.....*/

		+ " < \u0461 , \u0460"  // CYRILLIC OMEGA
		+ " < \u0463 , \u0462"  // CYRILLIC YAT
		+ " < \u0465 , \u0464"  // CYRILLIC IOTIFIED E
		+ " < \u0467 , \u0466"  // CYRILLIC LITTLE YUS
		+ " < \u0469 , \u0468"  // CYRILLIC IOTIFIED LITTLE YUS
		+ " < \u046B , \u046A"  // CYRILLIC BIG YUS
		+ " < \u046D , \u046C"  // CYRILLIC IOTIFIED BIG YUS
		+ " < \u046F , \u046E"  // CYRILLIC KSI
		+ " < \u0471 , \u0470"  // CYRILLIC PSI
		+ " < \u0473 , \u0472"  // CYRILLIC FITA
		+ " < \u0475 , \u0474"  // CYRILLIC IZHITSA
		+ " < \u0479 , \u0478"  // CYRILLIC UK
		+ " < \u047B , \u047A"  // CYRILLIC ROUND OMEGA
		+ " < \u047D , \u047C"  // CYRILLIC OMEGA WITH TITLO
		+ " < \u047F , \u047E"  // CYRILLIC OT
		+ " < \u0481 , \u0480"  // CYRILLIC KOPPA
		+ " < \u0491 , \u0490"  // CYRILLIC GHE WITH UPTURN
		+ " < \u0493 , \u0492"  // CYRILLIC GHE WITH STROKE
		+ " < \u0495 , \u0494"  // CYRILLIC GHE WITH MIDDLE HOOK
		+ " < \u0497 , \u0496"  // CYRILLIC ZHE WITH DESCENDER
		+ " < \u0499 , \u0498"  // CYRILLIC ZE WITH DESCENDER
		+ " < \u049B , \u049A"  // CYRILLIC KA WITH DESCENDER
		+ " < \u049D , \u049C"  // CYRILLIC KA WITH VERTICAL STROKE
		+ " < \u049F , \u049E"  // CYRILLIC KA WITH STROKE
		+ " < \u04A1 , \u04A0"  // CYRILLIC BASHKIR KA
		+ " < \u04A3 , \u04A2"  // CYRILLIC EN WITH DESCENDER
		+ " < \u04A5 , \u04A4"  // CYRILLIC LIGATURE EN GHE
		+ " < \u04A7 , \u04A6"  // CYRILLIC PE WITH MIDDLE HOOK
		+ " < \u04A9 , \u04A8"  // CYRILLIC ABKHASIAN HA
		+ " < \u04AB , \u04AA"  // CYRILLIC ES WITH DESCENDER
		+ " < \u04AD , \u04AC"  // CYRILLIC TE WITH DESCENDER
		+ " < \u04AF , \u04AE"  // CYRILLIC STRAIGHT U
		+ " < \u04B1 , \u04B0"  // CYRILLIC STRAIGHT U WITH STROKE
		+ " < \u04B3 , \u04B2"  // CYRILLIC HA WITH DESCENDER
		+ " < \u04B5 , \u04B4"  // CYRILLIC LIGATURE TE TSE
		+ " < \u04B7 , \u04B6"  // CYRILLIC CHE WITH DESCENDER
		+ " < \u04B9 , \u04B8"  // CYRILLIC CHE WITH VERTICAL STROKE
		+ " < \u04BB , \u04BA"  // CYRILLIC SHHA
		+ " < \u04BD , \u04BC"  // CYRILLIC ABKHASIAN CHE
		+ " < \u04BF , \u04BE"  // CYRILLIC ABKHASIAN CHE WITH DESCENDER
		+ " < \u04C4 , \u04C3"  // CYRILLIC KA WITH HOOK
		+ " < \u04C8 , \u04C7"  // CYRILLIC EN WITH HOOK
		+ " < \u04CC , \u04CB"  // CYRILLIC KHAKASSIAN CHE
    };
}
