/*
 * @(#)LocaleElements_pt.java	1.4 97/02/24
 *
 * (C) Copyright Taligent, Inc. 1996, 1997 - All Rights Reserved
 * (C) Copyright IBM Corp. 1996, 1997 - All Rights Reserved
 *
 * Portions copyright (c) 1996 Sun Microsystems, Inc. All Rights Reserved.
 *
 *   The original version of this source code and documentation is copyrighted
 * and owned by Taligent, Inc., a wholly-owned subsidiary of IBM. These
 * materials are provided under terms of a License Agreement between Taligent
 * and Sun. This technology is protected by multiple US and International
 * patents. This notice and attribution to Taligent may not be removed.
 *   Taligent is a registered trademark of Taligent, Inc.
 *
 * Permission to use, copy, modify, and distribute this software
 * and its documentation for NON-COMMERCIAL purposes and without
 * fee is hereby granted provided that this copyright notice
 * appears in all copies. Please refer to the file "copyright.html"
 * for further important copyright and licensing information.
 *
 * SUN MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF
 * THE SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
 * TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE, OR NON-INFRINGEMENT. SUN SHALL NOT BE LIABLE FOR
 * ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR
 * DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
 *
 */

/**
 *
 * Table of Java supplied standard locale elements
 *
 * automatically generated by java LocaleTool LocaleElements.java
 *
 * Date Created: Wed Aug 21 15:47:57  1996
 *
 *     Locale Elements and Patterns:  last update 10/23/96
 *
 *
 */

// WARNING : the format of this file will change in the future!

package java.text.resources;

public class LocaleElements_pt extends LocaleData {

    public LocaleElements_pt() {
        super.init(table);
    }

    static String table []={
        "pt_PT", /*locale id based on iso codes*/
        "0816", /*Windows id*/
        "ptg", /*iso-3 abbrev lang name*/
        "PRT", /*iso-3 abbrev country name*/
        "en_Portuguese; de_Portugiesisch; fr_portugais; pt_português", /*language names*/
        "en_Portugal; de_Portugal; fr_Portugal; pt_Portugal", /*country names*/
        "Janeiro", /*january*/
        "Fevereiro", /*february*/
        "Março", /*march*/
        "Abril", /*april*/
        "Maio", /*may*/
        "Junho", /*june*/
        "Julho", /*july*/
        "Agosto", /*august*/
        "Setembro", /*september*/
        "Outubro", /*october*/
        "Novembro", /*november*/
        "Dezembro", /*december*/
        "", /*month 13 if applicable*/
        "Jan", /*abb january*/
        "Fev", /*abb february*/
        "Mar", /*abb march*/
        "Abr", /*abb april*/
        "Mai", /*abb may*/
        "Jun", /*abb june*/
        "Jul", /*abb july*/
        "Ago", /*abb august*/
        "Set", /*abb september*/
        "Out", /*abb october*/
        "Nov", /*abb november*/
        "Dez", /*abb december*/
        "", /*abb month 13 if applicable*/
        "Domingo", /*Sunday*/
        "Segunda-feira", /*Monday*/
        "Terça-feira", /*Tuesday*/
        "Quarta-feira", /*Wednesday*/
        "Quinta-feira", /*Thursday*/
        "Sexta-feira", /*Friday*/
        "Sábado", /*Saturday*/
        "Dom", /*abb Sunday*/
        "Seg", /*abb Monday*/
        "Ter", /*abb Tuesday*/
        "Qua", /*abb Wednesday*/
        "Qui", /*abb Thursday*/
        "Sex", /*abb Friday*/
        "Sáb", /*abb Saturday*/
        "AM", /*am marker*/
        "PM", /*pm marker*/
        "BC;AD", /*era strings*/
        "#,##0.###;-#,##0.###", /*decimal pattern*/
        "#,##0.00 Esc.;-#,##0.00 Esc.", /*currency pattern*/
        "#,##0%", /*percent pattern*/
        ",", /*decimal separator*/
        ".", /*group (thousands) separator*/
        ";", /*list separator*/
        "%", /*percent sign*/
        "0", /*native 0 digit*/
        "#", /*pattern digit*/
        "-", /*minus sign*/
        "E", /*exponential*/
        "Esc.", /*local currency symbol*/
        "PTE", /*intl currency symbol*/
        "$", /*monetary decimal separator*/
        "HH'H'mm'm' z", /*full time pattern*/
        "H:mm:ss z", /*long time pattern*/
        "H:mm:ss", /*medium time pattern*/
        "H:mm", /*short time pattern*/
        "EEEE, d' de 'MMMM' de 'yyyy", /*full date pattern*/
        "d' de 'MMMM' de 'yyyy", /*long date pattern*/
        "d/MMM/yy", /*medium date pattern*/
        "dd-MM-yyyy", /*short date pattern*/
        "{1} {0}", /*date-time pattern*/
        "2", /*first day of week*/
        "1", /*min days in first week*/
        ""
    };
}
