/*
 * Copyright 2002 Sun Microsystems, Inc. All rights reserved.
 * SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */
package org.omg.CORBA;


/**
* org/omg/CORBA/PolicyOperations.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from ../../../../../src/share/classes/org/omg/PortableServer/corba.idl
* Saturday, July 17, 1999 12:26:20 AM PDT
*/

public interface PolicyOperations 
{

  /** Return the constant value that corresponds to the 
  		* type of the policy object.  The values of 
  		* the polivy objectys are allocated by the OMG.
  		* New values for PolicyType should be obtained from the OMG by
  		* sending mail to request@omg.org.  In general the constant
  		* values that are allocated are defined in conjunction with
  		* the definition of the corresponding policy object.
  		* @return the constant value that corresponds to the type of
  		* the policy object.
  		*/
  int policy_type ();

  /** Copies the policy object. The copy does not retain any
  		* relationships that the policy had with any domain or object.
  		* @return the copy of the policy object.
  		*/
  org.omg.CORBA.Policy copy ();

  /** Destroys the policy object.  It is the responsibility of
  		* the policy object to determine whether it can be destroyed.
  		*/
  void destroy ();
} // interface PolicyOperations
