/*
 * Copyright 2002 Sun Microsystems, Inc. All rights reserved.
 * SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */

/**
* org/omg/CosNaming/BindingIterator.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from nameservice.idl
* Wednesday, January 26, 2000 3:34:52 PM PST
*/

package org.omg.CosNaming;
/**
* The BindingIterator interface allows a client to iterate through
* the bindings using the next_one or next_n operations.
** The bindings iterator is obtained by using the <tt>list</tt>
* method on the <tt>NamingContext</tt>. 
* @see org.omg.CosNaming.NamingContext#list
*/

public interface BindingIterator extends BindingIteratorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity
{
} // interface BindingIterator

