package com.sun.java.swing.plaf.gtk.resources;

import java.util.ListResourceBundle;

public final class gtk_it extends ListResourceBundle {
    protected final Object[][] getContents() {
        return new Object[][] {
            { "FileChooser.acceptAllFileFilterText", "Tutti i file" },
            { "FileChooser.cancelButtonMnemonic", "65" },
            { "FileChooser.cancelButtonText", "Annulla" },
            { "FileChooser.cancelButtonToolTipText", "Chiude la finestra di dialogo di selezione file." },
            { "FileChooser.deleteFileButtonMnemonic", "76" },
            { "FileChooser.deleteFileButtonText", "Elimina file" },
            { "FileChooser.filesLabelMnemonic", "70" },
            { "FileChooser.filesLabelText", "File" },
            { "FileChooser.filterLabelText", "Filtro:" },
            { "FileChooser.foldersLabelMnemonic", "84" },
            { "FileChooser.foldersLabelText", "Cartelle" },
            { "FileChooser.newFolderButtonMnemonic", "78" },
            { "FileChooser.newFolderButtonText", "Nuova cartella" },
            { "FileChooser.newFolderDialogText", "Nome della cartella:" },
            { "FileChooser.newFolderNoDirectoryErrorText", "Errore durante la creazione della directory \"{0}\": file o directory inesistente" },
            { "FileChooser.newFolderNoDirectoryErrorTitleText", "Errore" },
            { "FileChooser.openButtonMnemonic", "79" },
            { "FileChooser.openButtonText", "OK" },
            { "FileChooser.openButtonToolTipText", "Apre il file selezionato." },
            { "FileChooser.openDialogTitleText", "Apri" },
            { "FileChooser.pathLabelMnemonic", "83" },
            { "FileChooser.pathLabelText", "Selezione:" },
            { "FileChooser.renameFileButtonMnemonic", "82" },
            { "FileChooser.renameFileButtonText", "Rinomina file" },
            { "FileChooser.renameFileDialogText", "Rinomina file \"{0}\" in" },
            { "FileChooser.renameFileErrorText", "Errore durante la ridenominazione del file \"{0}\" in \"{1}\"" },
            { "FileChooser.renameFileErrorTitle", "Errore" },
            { "FileChooser.saveButtonMnemonic", "79" },
            { "FileChooser.saveButtonText", "OK" },
            { "FileChooser.saveButtonToolTipText", "Salva il file selezionato." },
            { "FileChooser.saveDialogTitleText", "Salva" },
            { "GTKColorChooserPanel.blueMnemonic", "66" },
            { "GTKColorChooserPanel.blueText", "Blu:" },
            { "GTKColorChooserPanel.colorNameMnemonic", "78" },
            { "GTKColorChooserPanel.colorNameText", "Nome colore:" },
            { "GTKColorChooserPanel.greenMnemonic", "69" },
            { "GTKColorChooserPanel.greenText", "Verde:" },
            { "GTKColorChooserPanel.hueMnemonic", "84" },
            { "GTKColorChooserPanel.hueText", "Ton.:" },
            { "GTKColorChooserPanel.mnemonic", "71" },
            { "GTKColorChooserPanel.nameText", "Selezione colore GTK" },
            { "GTKColorChooserPanel.redMnemonic", "79" },
            { "GTKColorChooserPanel.redText", "Rosso:" },
            { "GTKColorChooserPanel.saturationMnemonic", "83" },
            { "GTKColorChooserPanel.saturationText", "Saturazione:" },
            { "GTKColorChooserPanel.valueMnemonic", "86" },
            { "GTKColorChooserPanel.valueText", "Valore:" },
            { "OptionPane.cancelButtonMnemonic", "65" },
            { "OptionPane.cancelButtonText", "Annulla" },
            { "OptionPane.okButtonMnemonic", "79" },
            { "OptionPane.okButtonText", "OK" },
        };
    }
}
