package com.sun.java.swing.plaf.gtk.resources;

import java.util.ListResourceBundle;

public final class gtk_es extends ListResourceBundle {
    protected final Object[][] getContents() {
        return new Object[][] {
            { "FileChooser.acceptAllFileFilterText", "Todos los Archivos" },
            { "FileChooser.cancelButtonMnemonic", "67" },
            { "FileChooser.cancelButtonText", "Cancelar" },
            { "FileChooser.cancelButtonToolTipText", "Abortar cuadro de di\u00E1logo del selector de archivos." },
            { "FileChooser.deleteFileButtonMnemonic", "80" },
            { "FileChooser.deleteFileButtonText", "Suprimir Archivo" },
            { "FileChooser.filesLabelMnemonic", "65" },
            { "FileChooser.filesLabelText", "Archivos" },
            { "FileChooser.filterLabelText", "Filtro:" },
            { "FileChooser.foldersLabelMnemonic", "84" },
            { "FileChooser.foldersLabelText", "Carpetas" },
            { "FileChooser.newFolderButtonMnemonic", "78" },
            { "FileChooser.newFolderButtonText", "Nueva Carpeta" },
            { "FileChooser.newFolderDialogText", "Nombre de la Carpeta:" },
            { "FileChooser.newFolderNoDirectoryErrorText", "Error al crear el directorio \"{0}\": no existe dicho archivo o directorio" },
            { "FileChooser.newFolderNoDirectoryErrorTitleText", "Error" },
            { "FileChooser.openButtonMnemonic", "65" },
            { "FileChooser.openButtonText", "Aceptar" },
            { "FileChooser.openButtonToolTipText", "Abrir el archivo seleccionado." },
            { "FileChooser.openDialogTitleText", "Abrir" },
            { "FileChooser.pathLabelMnemonic", "83" },
            { "FileChooser.pathLabelText", "Selecci\u00F3n:" },
            { "FileChooser.renameFileButtonMnemonic", "82" },
            { "FileChooser.renameFileButtonText", "Cambiar Nombre de Archivo" },
            { "FileChooser.renameFileDialogText", "Cambiar el nombre del archivo \"{0}\" por" },
            { "FileChooser.renameFileErrorText", "Error al cambiar el nombre del archivo \"{0}\" a \"{1}\"" },
            { "FileChooser.renameFileErrorTitle", "Error" },
            { "FileChooser.saveButtonMnemonic", "65" },
            { "FileChooser.saveButtonText", "Aceptar" },
            { "FileChooser.saveButtonToolTipText", "Guardar el archivo seleccionado." },
            { "FileChooser.saveDialogTitleText", "Guardar" },
            { "GTKColorChooserPanel.blueMnemonic", "65" },
            { "GTKColorChooserPanel.blueText", "Azul:" },
            { "GTKColorChooserPanel.colorNameMnemonic", "78" },
            { "GTKColorChooserPanel.colorNameText", "Nombre del Color:" },
            { "GTKColorChooserPanel.greenMnemonic", "69" },
            { "GTKColorChooserPanel.greenText", "Verde:" },
            { "GTKColorChooserPanel.hueMnemonic", "77" },
            { "GTKColorChooserPanel.hueText", "Mat:" },
            { "GTKColorChooserPanel.mnemonic", "71" },
            { "GTKColorChooserPanel.nameText", "Selector de Color para GTK" },
            { "GTKColorChooserPanel.redMnemonic", "74" },
            { "GTKColorChooserPanel.redText", "Rojo:" },
            { "GTKColorChooserPanel.saturationMnemonic", "83" },
            { "GTKColorChooserPanel.saturationText", "Saturaci\u00F3n:" },
            { "GTKColorChooserPanel.valueMnemonic", "86" },
            { "GTKColorChooserPanel.valueText", "Valor:" },
            { "OptionPane.cancelButtonMnemonic", "67" },
            { "OptionPane.cancelButtonText", "Cancelar" },
            { "OptionPane.okButtonMnemonic", "65" },
            { "OptionPane.okButtonText", "Aceptar" },
        };
    }
}
