package com.sun.java.swing.plaf.gtk.resources;

import java.util.ListResourceBundle;

public final class gtk_fr extends ListResourceBundle {
    protected final Object[][] getContents() {
        return new Object[][] {
            { "FileChooser.acceptAllFileFilterText", "Tous les fichiers" },
            { "FileChooser.cancelButtonMnemonic", "65" },
            { "FileChooser.cancelButtonText", "Annuler" },
            { "FileChooser.cancelButtonToolTipText", "Ferme la bo\u00EEte de dialogue du s\u00E9lecteur de fichiers." },
            { "FileChooser.deleteFileButtonMnemonic", "76" },
            { "FileChooser.deleteFileButtonText", "Supprimer le fichier" },
            { "FileChooser.filesLabelMnemonic", "70" },
            { "FileChooser.filesLabelText", "Fichiers" },
            { "FileChooser.filterLabelText", "Filtre :" },
            { "FileChooser.foldersLabelMnemonic", "68" },
            { "FileChooser.foldersLabelText", "Dossiers" },
            { "FileChooser.newFolderButtonMnemonic", "78" },
            { "FileChooser.newFolderButtonText", "Nouveau dossier" },
            { "FileChooser.newFolderDialogText", "Nom du dossier :" },
            { "FileChooser.newFolderNoDirectoryErrorText", "Erreur lors de la cr\u00E9ation du r\u00E9pertoire \"{0}\" : ce fichier ou r\u00E9pertoire n''existe pas" },
            { "FileChooser.newFolderNoDirectoryErrorTitleText", "Erreur" },
            { "FileChooser.openButtonMnemonic", "79" },
            { "FileChooser.openButtonText", "OK" },
            { "FileChooser.openButtonToolTipText", "Ouvre le fichier s\u00E9lectionn\u00E9." },
            { "FileChooser.openDialogTitleText", "Ouvrir" },
            { "FileChooser.pathLabelMnemonic", "83" },
            { "FileChooser.pathLabelText", "S\u00E9lection :" },
            { "FileChooser.renameFileButtonMnemonic", "82" },
            { "FileChooser.renameFileButtonText", "Renommer le fichier" },
            { "FileChooser.renameFileDialogText", "Renomme le fichier \"{0}\" en" },
            { "FileChooser.renameFileErrorText", "Erreur lors du changement de nom du fichier \"{0}\" en \"{1}\"" },
            { "FileChooser.renameFileErrorTitle", "Erreur" },
            { "FileChooser.saveButtonMnemonic", "79" },
            { "FileChooser.saveButtonText", "OK" },
            { "FileChooser.saveButtonToolTipText", "Enregistre le fichier s\u00E9lectionn\u00E9." },
            { "FileChooser.saveDialogTitleText", "Enregistrer" },
            { "GTKColorChooserPanel.blueMnemonic", "66" },
            { "GTKColorChooserPanel.blueText", "Bleu :" },
            { "GTKColorChooserPanel.colorNameMnemonic", "78" },
            { "GTKColorChooserPanel.colorNameText", "Nom de couleur :" },
            { "GTKColorChooserPanel.greenMnemonic", "69" },
            { "GTKColorChooserPanel.greenText", "Vert :" },
            { "GTKColorChooserPanel.hueMnemonic", "84" },
            { "GTKColorChooserPanel.hueText", "Teinte :" },
            { "GTKColorChooserPanel.mnemonic", "71" },
            { "GTKColorChooserPanel.nameText", "S\u00E9lecteur de couleurs GTK" },
            { "GTKColorChooserPanel.redMnemonic", "69" },
            { "GTKColorChooserPanel.redText", "Rouge\u00A0:" },
            { "GTKColorChooserPanel.saturationMnemonic", "83" },
            { "GTKColorChooserPanel.saturationText", "Saturation :" },
            { "GTKColorChooserPanel.valueMnemonic", "86" },
            { "GTKColorChooserPanel.valueText", "Valeur :" },
            { "OptionPane.cancelButtonMnemonic", "65" },
            { "OptionPane.cancelButtonText", "Annuler" },
            { "OptionPane.okButtonMnemonic", "79" },
            { "OptionPane.okButtonText", "OK" },
        };
    }
}
