package com.sun.java.swing.plaf.gtk.resources;

import java.util.ListResourceBundle;

public final class gtk_sv extends ListResourceBundle {
    protected final Object[][] getContents() {
        return new Object[][] {
            { "FileChooser.acceptAllFileFilterText", "Alla filer" },
            { "FileChooser.cancelButtonMnemonic", "65" },
            { "FileChooser.cancelButtonText", "Avbryt" },
            { "FileChooser.cancelButtonToolTipText", "Avbryt dialogrutan Filv\u00E4ljare." },
            { "FileChooser.deleteFileButtonMnemonic", "66" },
            { "FileChooser.deleteFileButtonText", "Ta bort fil" },
            { "FileChooser.filesLabelMnemonic", "70" },
            { "FileChooser.filesLabelText", "Filer" },
            { "FileChooser.filterLabelText", "Filter:" },
            { "FileChooser.foldersLabelMnemonic", "80" },
            { "FileChooser.foldersLabelText", "Mappar" },
            { "FileChooser.newFolderButtonMnemonic", "78" },
            { "FileChooser.newFolderButtonText", "Ny mapp" },
            { "FileChooser.newFolderDialogText", "Mapp:" },
            { "FileChooser.newFolderNoDirectoryErrorText", "Ett fel intr\u00E4ffade vid f\u00F6rs\u00F6k att skapa katalogen \"{0}\": Filen eller katalogen finns inte" },
            { "FileChooser.newFolderNoDirectoryErrorTitleText", "Fel" },
            { "FileChooser.openButtonMnemonic", "79" },
            { "FileChooser.openButtonText", "OK" },
            { "FileChooser.openButtonToolTipText", "\u00D6ppna vald fil." },
            { "FileChooser.openDialogTitleText", "\u00D6ppna" },
            { "FileChooser.pathLabelMnemonic", "85" },
            { "FileChooser.pathLabelText", "Urval:" },
            { "FileChooser.renameFileButtonMnemonic", "82" },
            { "FileChooser.renameFileButtonText", "\u00C4ndra namn p\u00E5 filen" },
            { "FileChooser.renameFileDialogText", "Namn\u00E4ndra fil \"{0}\" till" },
            { "FileChooser.renameFileErrorText", "Fel vid namn\u00E4ndring av fil \"{0}\" till \"{1}\"" },
            { "FileChooser.renameFileErrorTitle", "Fel" },
            { "FileChooser.saveButtonMnemonic", "79" },
            { "FileChooser.saveButtonText", "OK" },
            { "FileChooser.saveButtonToolTipText", "Spara vald fil." },
            { "FileChooser.saveDialogTitleText", "Spara" },
            { "GTKColorChooserPanel.blueMnemonic", "66" },
            { "GTKColorChooserPanel.blueText", "Bl\u00E5:" },
            { "GTKColorChooserPanel.colorNameMnemonic", "70" },
            { "GTKColorChooserPanel.colorNameText", "F\u00E4rgnamn:" },
            { "GTKColorChooserPanel.greenMnemonic", "71" },
            { "GTKColorChooserPanel.greenText", "Gr\u00F6n:" },
            { "GTKColorChooserPanel.hueMnemonic", "78" },
            { "GTKColorChooserPanel.hueText", "Nyans:" },
            { "GTKColorChooserPanel.mnemonic", "71" },
            { "GTKColorChooserPanel.nameText", "GTK-f\u00E4rgv\u00E4ljaren" },
            { "GTKColorChooserPanel.redMnemonic", "82" },
            { "GTKColorChooserPanel.redText", "R\u00F6d:" },
            { "GTKColorChooserPanel.saturationMnemonic", "77" },
            { "GTKColorChooserPanel.saturationText", "M\u00E4ttnad:" },
            { "GTKColorChooserPanel.valueMnemonic", "86" },
            { "GTKColorChooserPanel.valueText", "V\u00E4rde:" },
            { "OptionPane.cancelButtonMnemonic", "65" },
            { "OptionPane.cancelButtonText", "Avbryt" },
            { "OptionPane.okButtonMnemonic", "79" },
            { "OptionPane.okButtonText", "OK" },
        };
    }
}
