package com.sun.java.swing.plaf.gtk.resources;

import java.util.ListResourceBundle;

public final class gtk_pt_BR extends ListResourceBundle {
    protected final Object[][] getContents() {
        return new Object[][] {
            { "FileChooser.acceptAllFileFilterText", "Todos os Arquivos" },
            { "FileChooser.cancelButtonMnemonic", "67" },
            { "FileChooser.cancelButtonText", "Cancelar" },
            { "FileChooser.cancelButtonToolTipText", "Abortar caixa de di\u00E1logo do seletor de arquivos." },
            { "FileChooser.deleteFileButtonMnemonic", "76" },
            { "FileChooser.deleteFileButtonText", "Deletar Arquivo" },
            { "FileChooser.filesLabelMnemonic", "65" },
            { "FileChooser.filesLabelText", "Arquivos" },
            { "FileChooser.filterLabelText", "Filtro:" },
            { "FileChooser.foldersLabelMnemonic", "80" },
            { "FileChooser.foldersLabelText", "Pastas" },
            { "FileChooser.newFolderButtonMnemonic", "78" },
            { "FileChooser.newFolderButtonText", "Nova Pasta" },
            { "FileChooser.newFolderDialogText", "Nome da pasta:" },
            { "FileChooser.newFolderNoDirectoryErrorText", "Erro ao criar o diret\u00F3rio \"{0}\": N\u00E3o h\u00E1 arquivo ou diret\u00F3rio" },
            { "FileChooser.newFolderNoDirectoryErrorTitleText", "Erro" },
            { "FileChooser.openButtonMnemonic", "79" },
            { "FileChooser.openButtonText", "OK" },
            { "FileChooser.openButtonToolTipText", "Abrir arquivo selecionado." },
            { "FileChooser.openDialogTitleText", "Abrir" },
            { "FileChooser.pathLabelMnemonic", "83" },
            { "FileChooser.pathLabelText", "Sele\u00E7\u00E3o:" },
            { "FileChooser.renameFileButtonMnemonic", "82" },
            { "FileChooser.renameFileButtonText", "Renomear Arquivo" },
            { "FileChooser.renameFileDialogText", "Renomear arquivo \"{0}\" por" },
            { "FileChooser.renameFileErrorText", "Erro ao renomear o arquivo \"{0}\" por \"{1}\"" },
            { "FileChooser.renameFileErrorTitle", "Erro" },
            { "FileChooser.saveButtonMnemonic", "79" },
            { "FileChooser.saveButtonText", "OK" },
            { "FileChooser.saveButtonToolTipText", "Salvar arquivo selecionado." },
            { "FileChooser.saveDialogTitleText", "Salvar" },
            { "GTKColorChooserPanel.blueMnemonic", "65" },
            { "GTKColorChooserPanel.blueText", "Azul:" },
            { "GTKColorChooserPanel.colorNameMnemonic", "78" },
            { "GTKColorChooserPanel.colorNameText", "Nome da Cor:" },
            { "GTKColorChooserPanel.greenMnemonic", "68" },
            { "GTKColorChooserPanel.greenText", "Verde:" },
            { "GTKColorChooserPanel.hueMnemonic", "77" },
            { "GTKColorChooserPanel.hueText", "Matiz:" },
            { "GTKColorChooserPanel.mnemonic", "71" },
            { "GTKColorChooserPanel.nameText", "Seletor de Cores do GTK" },
            { "GTKColorChooserPanel.redMnemonic", "69" },
            { "GTKColorChooserPanel.redText", "Vermelho:" },
            { "GTKColorChooserPanel.saturationMnemonic", "83" },
            { "GTKColorChooserPanel.saturationText", "Satura\u00E7\u00E3o:" },
            { "GTKColorChooserPanel.valueMnemonic", "86" },
            { "GTKColorChooserPanel.valueText", "Valor:" },
            { "OptionPane.cancelButtonMnemonic", "67" },
            { "OptionPane.cancelButtonText", "Cancelar" },
            { "OptionPane.okButtonMnemonic", "79" },
            { "OptionPane.okButtonText", "OK" },
        };
    }
}
