/*
 * @(#)file      JDMHostName.java
 * @(#)author    Sun Microsystems, Inc.
 * @(#)version   4.11
 * @(#)date      10/07/17
 *
 * Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 */


/* Generated By:JJTree: Do not edit this line. JDMHostName.java */

package com.sun.jmx.snmp.IPAcl;

import java.net.UnknownHostException;

/** 
 * @version     4.11     03/23/10 
 * @author      Sun Microsystems, Inc. 
 */ 
class JDMHostName extends Host {
  protected StringBuffer name = new StringBuffer();

  JDMHostName(int id) {
    super(id);
  }

  JDMHostName(Parser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
      return new JDMHostName(id);
  }

  public static Node jjtCreate(Parser p, int id) {
      return new JDMHostName(p, id);
  }
  
  protected String getHname() {
	return name.toString();
  }
  
  protected PrincipalImpl createAssociatedPrincipal() 
    throws UnknownHostException { 
      return new PrincipalImpl(name.toString());
  }
}
