/*
 * @(#)file      JDMInformInterestedHost.java
 * @(#)author    Sun Microsystems, Inc.
 * @(#)version   1.7
 * @(#)date      10/07/17
 *
 * Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */

/* Generated By:JJTree: Do not edit this line. JDMInformInterestedHost.java */

package com.sun.jmx.snmp.IPAcl;

class JDMInformInterestedHost extends SimpleNode {
    JDMInformInterestedHost(int id) {
        super(id);
    }

    JDMInformInterestedHost(Parser p, int id) {
        super(p, id);
    }

    public static Node jjtCreate(int id) {
        return new JDMInformInterestedHost(id);
    }

    public static Node jjtCreate(Parser p, int id) {
        return new JDMInformInterestedHost(p, id);
    }
}
