package com.sun.corba.se.ActivationIDL;


/**
* com/sun/corba/se/ActivationIDL/ServerManagerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../../../../../../src/share/classes/com/sun/corba/se/ActivationIDL/activation.idl
* Thursday, August 29, 2002 2:54:21 AM PDT
*/

public interface ServerManagerOperations  extends com.sun.corba.se.ActivationIDL.ActivatorOperations, com.sun.corba.se.ActivationIDL.LocatorOperations
{
} // interface ServerManagerOperations
