package com.sun.corba.se.ActivationIDL;


/**
* com/sun/corba/se/ActivationIDL/ServerManagerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../../../../../../src/share/classes/com/sun/corba/se/ActivationIDL/activation.idl
* Friday, June 20, 2003 2:21:23 AM PDT
*/

public interface ServerManagerOperations  extends com.sun.corba.se.ActivationIDL.ActivatorOperations, com.sun.corba.se.ActivationIDL.LocatorOperations
{
} // interface ServerManagerOperations
