/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>
/* Header for class java_lang_String */

#ifndef _Included_java_lang_String
#define _Included_java_lang_String

#pragma pack(4)

typedef struct Classjava_lang_String {
    struct HArrayOfChar *value;
    long offset;
    long count;
#undef java_lang_String_serialVersionUID
#define java_lang_String_serialVersionUID -6849794470754667710LL
} Classjava_lang_String;
HandleTo(java_lang_String);

#pragma pack()

#ifdef __cplusplus
extern "C" {
#endif
struct Hjava_lang_String;
extern struct Hjava_lang_String *java_lang_String_intern(struct Hjava_lang_String *);
#ifdef __cplusplus
}
#endif
#endif
