/*
 * @(#)SkeletonMismatchException.java	1.5 01/12/10
 *
 * Copyright 2002 Sun Microsystems, Inc. All rights reserved.
 * SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */

package java.rmi.server;

import java.rmi.RemoteException;

/**
 * This exception is thrown when a call is received that does not
 * match the available skeleton.  It indicates either that the
 * remote method names or signatures in this interface have changed or
 * that the stub class used to make the call and the skeleton
 * receiving the call were not generated by the same version of
 * the stub compiler (RMIC).
 */
public class SkeletonMismatchException extends RemoteException {

    private static final long serialVersionUID = -7780460454818859281L;

    /**
     * Create a new SkeletonMismatchException exception with a descriptive string.  */
    public SkeletonMismatchException(String s) {
	super(s);
    }

}
